// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: kernel/v1/business_chain.proto

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusinessChainService_GetLastDataHash_FullMethodName = "/trusted_space.kernel.v1.BusinessChainService/GetLastDataHash"
	BusinessChainService_QueryChain_FullMethodName      = "/trusted_space.kernel.v1.BusinessChainService/QueryChain"
)

// BusinessChainServiceClient is the client API for BusinessChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------------------------------
// 业务数据哈希链服务 (Business Chain Service)
// 用于连接器和内核之间的业务数据哈希链交互
// 注意：data_hash 的计算和签名已集成到 StreamData 流式传输过程中，
// 此服务仅用于查询和同步操作
// ------------------------------------------------------------
type BusinessChainServiceClient interface {
	// 获取最新哈希：连接器从内核获取指定频道的最新data_hash（用于本地无记录时同步）
	GetLastDataHash(ctx context.Context, in *GetLastDataHashRequest, opts ...grpc.CallOption) (*GetLastDataHashResponse, error)
	// 查询哈希链：连接器查询指定频道的完整哈希链
	QueryChain(ctx context.Context, in *QueryChainRequest, opts ...grpc.CallOption) (*QueryChainResponse, error)
}

type businessChainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessChainServiceClient(cc grpc.ClientConnInterface) BusinessChainServiceClient {
	return &businessChainServiceClient{cc}
}

func (c *businessChainServiceClient) GetLastDataHash(ctx context.Context, in *GetLastDataHashRequest, opts ...grpc.CallOption) (*GetLastDataHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastDataHashResponse)
	err := c.cc.Invoke(ctx, BusinessChainService_GetLastDataHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessChainServiceClient) QueryChain(ctx context.Context, in *QueryChainRequest, opts ...grpc.CallOption) (*QueryChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryChainResponse)
	err := c.cc.Invoke(ctx, BusinessChainService_QueryChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessChainServiceServer is the server API for BusinessChainService service.
// All implementations must embed UnimplementedBusinessChainServiceServer
// for forward compatibility.
//
// ------------------------------------------------------------
// 业务数据哈希链服务 (Business Chain Service)
// 用于连接器和内核之间的业务数据哈希链交互
// 注意：data_hash 的计算和签名已集成到 StreamData 流式传输过程中，
// 此服务仅用于查询和同步操作
// ------------------------------------------------------------
type BusinessChainServiceServer interface {
	// 获取最新哈希：连接器从内核获取指定频道的最新data_hash（用于本地无记录时同步）
	GetLastDataHash(context.Context, *GetLastDataHashRequest) (*GetLastDataHashResponse, error)
	// 查询哈希链：连接器查询指定频道的完整哈希链
	QueryChain(context.Context, *QueryChainRequest) (*QueryChainResponse, error)
	mustEmbedUnimplementedBusinessChainServiceServer()
}

// UnimplementedBusinessChainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusinessChainServiceServer struct{}

func (UnimplementedBusinessChainServiceServer) GetLastDataHash(context.Context, *GetLastDataHashRequest) (*GetLastDataHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastDataHash not implemented")
}
func (UnimplementedBusinessChainServiceServer) QueryChain(context.Context, *QueryChainRequest) (*QueryChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryChain not implemented")
}
func (UnimplementedBusinessChainServiceServer) mustEmbedUnimplementedBusinessChainServiceServer() {}
func (UnimplementedBusinessChainServiceServer) testEmbeddedByValue()                              {}

// UnsafeBusinessChainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessChainServiceServer will
// result in compilation errors.
type UnsafeBusinessChainServiceServer interface {
	mustEmbedUnimplementedBusinessChainServiceServer()
}

func RegisterBusinessChainServiceServer(s grpc.ServiceRegistrar, srv BusinessChainServiceServer) {
	// If the following call panics, it indicates UnimplementedBusinessChainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusinessChainService_ServiceDesc, srv)
}

func _BusinessChainService_GetLastDataHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastDataHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessChainServiceServer).GetLastDataHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessChainService_GetLastDataHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessChainServiceServer).GetLastDataHash(ctx, req.(*GetLastDataHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessChainService_QueryChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessChainServiceServer).QueryChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessChainService_QueryChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessChainServiceServer).QueryChain(ctx, req.(*QueryChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusinessChainService_ServiceDesc is the grpc.ServiceDesc for BusinessChainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusinessChainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trusted_space.kernel.v1.BusinessChainService",
	HandlerType: (*BusinessChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastDataHash",
			Handler:    _BusinessChainService_GetLastDataHash_Handler,
		},
		{
			MethodName: "QueryChain",
			Handler:    _BusinessChainService_QueryChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kernel/v1/business_chain.proto",
}
