// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: kernel/v1/business_chain.proto

package kernelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------
// 获取最新哈希相关消息定义
// ------------------------------------------------------------
type GetLastDataHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 连接器ID
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`       // 频道ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastDataHashRequest) Reset() {
	*x = GetLastDataHashRequest{}
	mi := &file_kernel_v1_business_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastDataHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastDataHashRequest) ProtoMessage() {}

func (x *GetLastDataHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_business_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastDataHashRequest.ProtoReflect.Descriptor instead.
func (*GetLastDataHashRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_business_chain_proto_rawDescGZIP(), []int{0}
}

func (x *GetLastDataHashRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *GetLastDataHashRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetLastDataHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LastDataHash  string                 `protobuf:"bytes,2,opt,name=last_data_hash,json=lastDataHash,proto3" json:"last_data_hash,omitempty"` // 最新data_hash（如果是第一个包则为空字符串）
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastDataHashResponse) Reset() {
	*x = GetLastDataHashResponse{}
	mi := &file_kernel_v1_business_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastDataHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastDataHashResponse) ProtoMessage() {}

func (x *GetLastDataHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_business_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastDataHashResponse.ProtoReflect.Descriptor instead.
func (*GetLastDataHashResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_business_chain_proto_rawDescGZIP(), []int{1}
}

func (x *GetLastDataHashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLastDataHashResponse) GetLastDataHash() string {
	if x != nil {
		return x.LastDataHash
	}
	return ""
}

func (x *GetLastDataHashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ------------------------------------------------------------
// 查询哈希链相关消息定义
// ------------------------------------------------------------
type QueryChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 连接器ID
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`       // 频道ID
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                               // 限制返回记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChainRequest) Reset() {
	*x = QueryChainRequest{}
	mi := &file_kernel_v1_business_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChainRequest) ProtoMessage() {}

func (x *QueryChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_business_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChainRequest.ProtoReflect.Descriptor instead.
func (*QueryChainRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_business_chain_proto_rawDescGZIP(), []int{2}
}

func (x *QueryChainRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *QueryChainRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryChainRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ChainRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	DataHash      string                 `protobuf:"bytes,3,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`                // 业务数据哈希，ACK记录为空
	PrevDataHash  string                 `protobuf:"bytes,4,opt,name=prev_data_hash,json=prevDataHash,proto3" json:"prev_data_hash,omitempty"`  // 前一个数据包的哈希
	PrevSignature string                 `protobuf:"bytes,5,opt,name=prev_signature,json=prevSignature,proto3" json:"prev_signature,omitempty"` // 上一跳（kernel/connector）的 RSA 签名
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                              // 当前节点对 data_hash 的 RSA 签名
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainRecord) Reset() {
	*x = ChainRecord{}
	mi := &file_kernel_v1_business_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainRecord) ProtoMessage() {}

func (x *ChainRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_business_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainRecord.ProtoReflect.Descriptor instead.
func (*ChainRecord) Descriptor() ([]byte, []int) {
	return file_kernel_v1_business_chain_proto_rawDescGZIP(), []int{3}
}

func (x *ChainRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChainRecord) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChainRecord) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *ChainRecord) GetPrevDataHash() string {
	if x != nil {
		return x.PrevDataHash
	}
	return ""
}

func (x *ChainRecord) GetPrevSignature() string {
	if x != nil {
		return x.PrevSignature
	}
	return ""
}

func (x *ChainRecord) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ChainRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type QueryChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Records       []*ChainRecord         `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChainResponse) Reset() {
	*x = QueryChainResponse{}
	mi := &file_kernel_v1_business_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChainResponse) ProtoMessage() {}

func (x *QueryChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_business_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChainResponse.ProtoReflect.Descriptor instead.
func (*QueryChainResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_business_chain_proto_rawDescGZIP(), []int{4}
}

func (x *QueryChainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryChainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryChainResponse) GetRecords() []*ChainRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryChainResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_kernel_v1_business_chain_proto protoreflect.FileDescriptor

const file_kernel_v1_business_chain_proto_rawDesc = "" +
	"\n" +
	"\x1ekernel/v1/business_chain.proto\x12\x17trusted_space.kernel.v1\"Z\n" +
	"\x16GetLastDataHashRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"s\n" +
	"\x17GetLastDataHashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0elast_data_hash\x18\x02 \x01(\tR\flastDataHash\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"k\n" +
	"\x11QueryChainRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xe2\x01\n" +
	"\vChainRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tdata_hash\x18\x03 \x01(\tR\bdataHash\x12$\n" +
	"\x0eprev_data_hash\x18\x04 \x01(\tR\fprevDataHash\x12%\n" +
	"\x0eprev_signature\x18\x05 \x01(\tR\rprevSignature\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\xa9\x01\n" +
	"\x12QueryChainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\arecords\x18\x03 \x03(\v2$.trusted_space.kernel.v1.ChainRecordR\arecords\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount2\xf3\x01\n" +
	"\x14BusinessChainService\x12t\n" +
	"\x0fGetLastDataHash\x12/.trusted_space.kernel.v1.GetLastDataHashRequest\x1a0.trusted_space.kernel.v1.GetLastDataHashResponse\x12e\n" +
	"\n" +
	"QueryChain\x12*.trusted_space.kernel.v1.QueryChainRequest\x1a+.trusted_space.kernel.v1.QueryChainResponseB1Z/github.com/trusted-space/kernel/api/v1;kernelv1b\x06proto3"

var (
	file_kernel_v1_business_chain_proto_rawDescOnce sync.Once
	file_kernel_v1_business_chain_proto_rawDescData []byte
)

func file_kernel_v1_business_chain_proto_rawDescGZIP() []byte {
	file_kernel_v1_business_chain_proto_rawDescOnce.Do(func() {
		file_kernel_v1_business_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_v1_business_chain_proto_rawDesc), len(file_kernel_v1_business_chain_proto_rawDesc)))
	})
	return file_kernel_v1_business_chain_proto_rawDescData
}

var file_kernel_v1_business_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kernel_v1_business_chain_proto_goTypes = []any{
	(*GetLastDataHashRequest)(nil),  // 0: trusted_space.kernel.v1.GetLastDataHashRequest
	(*GetLastDataHashResponse)(nil), // 1: trusted_space.kernel.v1.GetLastDataHashResponse
	(*QueryChainRequest)(nil),       // 2: trusted_space.kernel.v1.QueryChainRequest
	(*ChainRecord)(nil),             // 3: trusted_space.kernel.v1.ChainRecord
	(*QueryChainResponse)(nil),      // 4: trusted_space.kernel.v1.QueryChainResponse
}
var file_kernel_v1_business_chain_proto_depIdxs = []int32{
	3, // 0: trusted_space.kernel.v1.QueryChainResponse.records:type_name -> trusted_space.kernel.v1.ChainRecord
	0, // 1: trusted_space.kernel.v1.BusinessChainService.GetLastDataHash:input_type -> trusted_space.kernel.v1.GetLastDataHashRequest
	2, // 2: trusted_space.kernel.v1.BusinessChainService.QueryChain:input_type -> trusted_space.kernel.v1.QueryChainRequest
	1, // 3: trusted_space.kernel.v1.BusinessChainService.GetLastDataHash:output_type -> trusted_space.kernel.v1.GetLastDataHashResponse
	4, // 4: trusted_space.kernel.v1.BusinessChainService.QueryChain:output_type -> trusted_space.kernel.v1.QueryChainResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kernel_v1_business_chain_proto_init() }
func file_kernel_v1_business_chain_proto_init() {
	if File_kernel_v1_business_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_v1_business_chain_proto_rawDesc), len(file_kernel_v1_business_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernel_v1_business_chain_proto_goTypes,
		DependencyIndexes: file_kernel_v1_business_chain_proto_depIdxs,
		MessageInfos:      file_kernel_v1_business_chain_proto_msgTypes,
	}.Build()
	File_kernel_v1_business_chain_proto = out.File
	file_kernel_v1_business_chain_proto_goTypes = nil
	file_kernel_v1_business_chain_proto_depIdxs = nil
}
