// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: kernel/v1/channel.proto

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelService_CreateChannel_FullMethodName              = "/trusted_space.kernel.v1.ChannelService/CreateChannel"
	ChannelService_StreamData_FullMethodName                 = "/trusted_space.kernel.v1.ChannelService/StreamData"
	ChannelService_SubscribeData_FullMethodName              = "/trusted_space.kernel.v1.ChannelService/SubscribeData"
	ChannelService_CloseChannel_FullMethodName               = "/trusted_space.kernel.v1.ChannelService/CloseChannel"
	ChannelService_NotifyChannelCreated_FullMethodName       = "/trusted_space.kernel.v1.ChannelService/NotifyChannelCreated"
	ChannelService_WaitForChannelNotification_FullMethodName = "/trusted_space.kernel.v1.ChannelService/WaitForChannelNotification"
	ChannelService_GetChannelInfo_FullMethodName             = "/trusted_space.kernel.v1.ChannelService/GetChannelInfo"
	ChannelService_ProposeChannel_FullMethodName             = "/trusted_space.kernel.v1.ChannelService/ProposeChannel"
	ChannelService_AcceptChannelProposal_FullMethodName      = "/trusted_space.kernel.v1.ChannelService/AcceptChannelProposal"
	ChannelService_RejectChannelProposal_FullMethodName      = "/trusted_space.kernel.v1.ChannelService/RejectChannelProposal"
	ChannelService_RequestChannelSubscription_FullMethodName = "/trusted_space.kernel.v1.ChannelService/RequestChannelSubscription"
	ChannelService_ApproveChannelSubscription_FullMethodName = "/trusted_space.kernel.v1.ChannelService/ApproveChannelSubscription"
	ChannelService_RejectChannelSubscription_FullMethodName  = "/trusted_space.kernel.v1.ChannelService/RejectChannelSubscription"
	ChannelService_RequestPermissionChange_FullMethodName    = "/trusted_space.kernel.v1.ChannelService/RequestPermissionChange"
	ChannelService_ApprovePermissionChange_FullMethodName    = "/trusted_space.kernel.v1.ChannelService/ApprovePermissionChange"
	ChannelService_RejectPermissionChange_FullMethodName     = "/trusted_space.kernel.v1.ChannelService/RejectPermissionChange"
	ChannelService_GetPermissionRequests_FullMethodName      = "/trusted_space.kernel.v1.ChannelService/GetPermissionRequests"
	ChannelService_SendAck_FullMethodName                    = "/trusted_space.kernel.v1.ChannelService/SendAck"
)

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------------------------------
// 流通与频道服务 (Channel Service)
// ------------------------------------------------------------
// 对应文档中的"频道(Channel)"概念
type ChannelServiceClient interface {
	// 请求创建一个数据传输频道
	// 如果指定create_related_channels=true，会自动创建关联的控制和日志频道
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateChannelResponse, error)
	// 在频道内推送数据 (连接器 -> 内核)
	// 内核作为中转服务，接收流数据
	StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataPacket, TransferStatus], error)
	// 接收数据 (内核 -> 连接器)
	SubscribeData(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataPacket], error)
	// 关闭频道
	CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (*CloseChannelResponse, error)
	// 通知服务：接收频道创建通知
	NotifyChannelCreated(ctx context.Context, in *NotifyChannelRequest, opts ...grpc.CallOption) (*NotifyChannelResponse, error)
	// 等待频道通知（接收方使用，等待被通知有新的频道）
	WaitForChannelNotification(ctx context.Context, in *WaitNotificationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChannelNotification], error)
	// 获取频道信息
	GetChannelInfo(ctx context.Context, in *GetChannelInfoRequest, opts ...grpc.CallOption) (*GetChannelInfoResponse, error)
	// 频道协商相关服务（两阶段频道创建）
	ProposeChannel(ctx context.Context, in *ProposeChannelRequest, opts ...grpc.CallOption) (*ProposeChannelResponse, error)
	AcceptChannelProposal(ctx context.Context, in *AcceptChannelProposalRequest, opts ...grpc.CallOption) (*AcceptChannelProposalResponse, error)
	RejectChannelProposal(ctx context.Context, in *RejectChannelProposalRequest, opts ...grpc.CallOption) (*RejectChannelProposalResponse, error)
	// 频道订阅申请相关服务（频道外连接器使用）
	RequestChannelSubscription(ctx context.Context, in *RequestChannelSubscriptionRequest, opts ...grpc.CallOption) (*RequestChannelSubscriptionResponse, error)
	ApproveChannelSubscription(ctx context.Context, in *ApproveChannelSubscriptionRequest, opts ...grpc.CallOption) (*ApproveChannelSubscriptionResponse, error)
	RejectChannelSubscription(ctx context.Context, in *RejectChannelSubscriptionRequest, opts ...grpc.CallOption) (*RejectChannelSubscriptionResponse, error)
	// 权限变更相关服务（频道内连接器使用）
	RequestPermissionChange(ctx context.Context, in *RequestPermissionChangeRequest, opts ...grpc.CallOption) (*RequestPermissionChangeResponse, error)
	ApprovePermissionChange(ctx context.Context, in *ApprovePermissionChangeRequest, opts ...grpc.CallOption) (*ApprovePermissionChangeResponse, error)
	RejectPermissionChange(ctx context.Context, in *RejectPermissionChangeRequest, opts ...grpc.CallOption) (*RejectPermissionChangeResponse, error)
	GetPermissionRequests(ctx context.Context, in *GetPermissionRequestsRequest, opts ...grpc.CallOption) (*GetPermissionRequestsResponse, error)
	// ACK 发送：接收方（connector-B）发送 ACK 给内核，内核转发给发送方（connector-A）
	SendAck(ctx context.Context, in *AckPacket, opts ...grpc.CallOption) (*SendAckResponse, error)
}

type channelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelServiceClient(cc grpc.ClientConnInterface) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChannelResponse)
	err := c.cc.Invoke(ctx, ChannelService_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataPacket, TransferStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChannelService_ServiceDesc.Streams[0], ChannelService_StreamData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataPacket, TransferStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_StreamDataClient = grpc.BidiStreamingClient[DataPacket, TransferStatus]

func (c *channelServiceClient) SubscribeData(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChannelService_ServiceDesc.Streams[1], ChannelService_SubscribeData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, DataPacket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_SubscribeDataClient = grpc.ServerStreamingClient[DataPacket]

func (c *channelServiceClient) CloseChannel(ctx context.Context, in *CloseChannelRequest, opts ...grpc.CallOption) (*CloseChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseChannelResponse)
	err := c.cc.Invoke(ctx, ChannelService_CloseChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) NotifyChannelCreated(ctx context.Context, in *NotifyChannelRequest, opts ...grpc.CallOption) (*NotifyChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyChannelResponse)
	err := c.cc.Invoke(ctx, ChannelService_NotifyChannelCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) WaitForChannelNotification(ctx context.Context, in *WaitNotificationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChannelNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChannelService_ServiceDesc.Streams[2], ChannelService_WaitForChannelNotification_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WaitNotificationRequest, ChannelNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_WaitForChannelNotificationClient = grpc.ServerStreamingClient[ChannelNotification]

func (c *channelServiceClient) GetChannelInfo(ctx context.Context, in *GetChannelInfoRequest, opts ...grpc.CallOption) (*GetChannelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChannelInfoResponse)
	err := c.cc.Invoke(ctx, ChannelService_GetChannelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ProposeChannel(ctx context.Context, in *ProposeChannelRequest, opts ...grpc.CallOption) (*ProposeChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeChannelResponse)
	err := c.cc.Invoke(ctx, ChannelService_ProposeChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) AcceptChannelProposal(ctx context.Context, in *AcceptChannelProposalRequest, opts ...grpc.CallOption) (*AcceptChannelProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptChannelProposalResponse)
	err := c.cc.Invoke(ctx, ChannelService_AcceptChannelProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) RejectChannelProposal(ctx context.Context, in *RejectChannelProposalRequest, opts ...grpc.CallOption) (*RejectChannelProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectChannelProposalResponse)
	err := c.cc.Invoke(ctx, ChannelService_RejectChannelProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) RequestChannelSubscription(ctx context.Context, in *RequestChannelSubscriptionRequest, opts ...grpc.CallOption) (*RequestChannelSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestChannelSubscriptionResponse)
	err := c.cc.Invoke(ctx, ChannelService_RequestChannelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ApproveChannelSubscription(ctx context.Context, in *ApproveChannelSubscriptionRequest, opts ...grpc.CallOption) (*ApproveChannelSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveChannelSubscriptionResponse)
	err := c.cc.Invoke(ctx, ChannelService_ApproveChannelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) RejectChannelSubscription(ctx context.Context, in *RejectChannelSubscriptionRequest, opts ...grpc.CallOption) (*RejectChannelSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectChannelSubscriptionResponse)
	err := c.cc.Invoke(ctx, ChannelService_RejectChannelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) RequestPermissionChange(ctx context.Context, in *RequestPermissionChangeRequest, opts ...grpc.CallOption) (*RequestPermissionChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPermissionChangeResponse)
	err := c.cc.Invoke(ctx, ChannelService_RequestPermissionChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ApprovePermissionChange(ctx context.Context, in *ApprovePermissionChangeRequest, opts ...grpc.CallOption) (*ApprovePermissionChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePermissionChangeResponse)
	err := c.cc.Invoke(ctx, ChannelService_ApprovePermissionChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) RejectPermissionChange(ctx context.Context, in *RejectPermissionChangeRequest, opts ...grpc.CallOption) (*RejectPermissionChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectPermissionChangeResponse)
	err := c.cc.Invoke(ctx, ChannelService_RejectPermissionChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) GetPermissionRequests(ctx context.Context, in *GetPermissionRequestsRequest, opts ...grpc.CallOption) (*GetPermissionRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionRequestsResponse)
	err := c.cc.Invoke(ctx, ChannelService_GetPermissionRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) SendAck(ctx context.Context, in *AckPacket, opts ...grpc.CallOption) (*SendAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAckResponse)
	err := c.cc.Invoke(ctx, ChannelService_SendAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServiceServer is the server API for ChannelService service.
// All implementations must embed UnimplementedChannelServiceServer
// for forward compatibility.
//
// ------------------------------------------------------------
// 流通与频道服务 (Channel Service)
// ------------------------------------------------------------
// 对应文档中的"频道(Channel)"概念
type ChannelServiceServer interface {
	// 请求创建一个数据传输频道
	// 如果指定create_related_channels=true，会自动创建关联的控制和日志频道
	CreateChannel(context.Context, *CreateChannelRequest) (*CreateChannelResponse, error)
	// 在频道内推送数据 (连接器 -> 内核)
	// 内核作为中转服务，接收流数据
	StreamData(grpc.BidiStreamingServer[DataPacket, TransferStatus]) error
	// 接收数据 (内核 -> 连接器)
	SubscribeData(*SubscribeRequest, grpc.ServerStreamingServer[DataPacket]) error
	// 关闭频道
	CloseChannel(context.Context, *CloseChannelRequest) (*CloseChannelResponse, error)
	// 通知服务：接收频道创建通知
	NotifyChannelCreated(context.Context, *NotifyChannelRequest) (*NotifyChannelResponse, error)
	// 等待频道通知（接收方使用，等待被通知有新的频道）
	WaitForChannelNotification(*WaitNotificationRequest, grpc.ServerStreamingServer[ChannelNotification]) error
	// 获取频道信息
	GetChannelInfo(context.Context, *GetChannelInfoRequest) (*GetChannelInfoResponse, error)
	// 频道协商相关服务（两阶段频道创建）
	ProposeChannel(context.Context, *ProposeChannelRequest) (*ProposeChannelResponse, error)
	AcceptChannelProposal(context.Context, *AcceptChannelProposalRequest) (*AcceptChannelProposalResponse, error)
	RejectChannelProposal(context.Context, *RejectChannelProposalRequest) (*RejectChannelProposalResponse, error)
	// 频道订阅申请相关服务（频道外连接器使用）
	RequestChannelSubscription(context.Context, *RequestChannelSubscriptionRequest) (*RequestChannelSubscriptionResponse, error)
	ApproveChannelSubscription(context.Context, *ApproveChannelSubscriptionRequest) (*ApproveChannelSubscriptionResponse, error)
	RejectChannelSubscription(context.Context, *RejectChannelSubscriptionRequest) (*RejectChannelSubscriptionResponse, error)
	// 权限变更相关服务（频道内连接器使用）
	RequestPermissionChange(context.Context, *RequestPermissionChangeRequest) (*RequestPermissionChangeResponse, error)
	ApprovePermissionChange(context.Context, *ApprovePermissionChangeRequest) (*ApprovePermissionChangeResponse, error)
	RejectPermissionChange(context.Context, *RejectPermissionChangeRequest) (*RejectPermissionChangeResponse, error)
	GetPermissionRequests(context.Context, *GetPermissionRequestsRequest) (*GetPermissionRequestsResponse, error)
	// ACK 发送：接收方（connector-B）发送 ACK 给内核，内核转发给发送方（connector-A）
	SendAck(context.Context, *AckPacket) (*SendAckResponse, error)
	mustEmbedUnimplementedChannelServiceServer()
}

// UnimplementedChannelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelServiceServer struct{}

func (UnimplementedChannelServiceServer) CreateChannel(context.Context, *CreateChannelRequest) (*CreateChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedChannelServiceServer) StreamData(grpc.BidiStreamingServer[DataPacket, TransferStatus]) error {
	return status.Error(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedChannelServiceServer) SubscribeData(*SubscribeRequest, grpc.ServerStreamingServer[DataPacket]) error {
	return status.Error(codes.Unimplemented, "method SubscribeData not implemented")
}
func (UnimplementedChannelServiceServer) CloseChannel(context.Context, *CloseChannelRequest) (*CloseChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseChannel not implemented")
}
func (UnimplementedChannelServiceServer) NotifyChannelCreated(context.Context, *NotifyChannelRequest) (*NotifyChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyChannelCreated not implemented")
}
func (UnimplementedChannelServiceServer) WaitForChannelNotification(*WaitNotificationRequest, grpc.ServerStreamingServer[ChannelNotification]) error {
	return status.Error(codes.Unimplemented, "method WaitForChannelNotification not implemented")
}
func (UnimplementedChannelServiceServer) GetChannelInfo(context.Context, *GetChannelInfoRequest) (*GetChannelInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChannelInfo not implemented")
}
func (UnimplementedChannelServiceServer) ProposeChannel(context.Context, *ProposeChannelRequest) (*ProposeChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeChannel not implemented")
}
func (UnimplementedChannelServiceServer) AcceptChannelProposal(context.Context, *AcceptChannelProposalRequest) (*AcceptChannelProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptChannelProposal not implemented")
}
func (UnimplementedChannelServiceServer) RejectChannelProposal(context.Context, *RejectChannelProposalRequest) (*RejectChannelProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectChannelProposal not implemented")
}
func (UnimplementedChannelServiceServer) RequestChannelSubscription(context.Context, *RequestChannelSubscriptionRequest) (*RequestChannelSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestChannelSubscription not implemented")
}
func (UnimplementedChannelServiceServer) ApproveChannelSubscription(context.Context, *ApproveChannelSubscriptionRequest) (*ApproveChannelSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveChannelSubscription not implemented")
}
func (UnimplementedChannelServiceServer) RejectChannelSubscription(context.Context, *RejectChannelSubscriptionRequest) (*RejectChannelSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectChannelSubscription not implemented")
}
func (UnimplementedChannelServiceServer) RequestPermissionChange(context.Context, *RequestPermissionChangeRequest) (*RequestPermissionChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPermissionChange not implemented")
}
func (UnimplementedChannelServiceServer) ApprovePermissionChange(context.Context, *ApprovePermissionChangeRequest) (*ApprovePermissionChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePermissionChange not implemented")
}
func (UnimplementedChannelServiceServer) RejectPermissionChange(context.Context, *RejectPermissionChangeRequest) (*RejectPermissionChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectPermissionChange not implemented")
}
func (UnimplementedChannelServiceServer) GetPermissionRequests(context.Context, *GetPermissionRequestsRequest) (*GetPermissionRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissionRequests not implemented")
}
func (UnimplementedChannelServiceServer) SendAck(context.Context, *AckPacket) (*SendAckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAck not implemented")
}
func (UnimplementedChannelServiceServer) mustEmbedUnimplementedChannelServiceServer() {}
func (UnimplementedChannelServiceServer) testEmbeddedByValue()                        {}

// UnsafeChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServiceServer will
// result in compilation errors.
type UnsafeChannelServiceServer interface {
	mustEmbedUnimplementedChannelServiceServer()
}

func RegisterChannelServiceServer(s grpc.ServiceRegistrar, srv ChannelServiceServer) {
	// If the following call panics, it indicates UnimplementedChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelService_ServiceDesc, srv)
}

func _ChannelService_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChannelServiceServer).StreamData(&grpc.GenericServerStream[DataPacket, TransferStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_StreamDataServer = grpc.BidiStreamingServer[DataPacket, TransferStatus]

func _ChannelService_SubscribeData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChannelServiceServer).SubscribeData(m, &grpc.GenericServerStream[SubscribeRequest, DataPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_SubscribeDataServer = grpc.ServerStreamingServer[DataPacket]

func _ChannelService_CloseChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).CloseChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_CloseChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).CloseChannel(ctx, req.(*CloseChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_NotifyChannelCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).NotifyChannelCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_NotifyChannelCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).NotifyChannelCreated(ctx, req.(*NotifyChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_WaitForChannelNotification_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WaitNotificationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChannelServiceServer).WaitForChannelNotification(m, &grpc.GenericServerStream[WaitNotificationRequest, ChannelNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChannelService_WaitForChannelNotificationServer = grpc.ServerStreamingServer[ChannelNotification]

func _ChannelService_GetChannelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).GetChannelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_GetChannelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).GetChannelInfo(ctx, req.(*GetChannelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ProposeChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ProposeChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ProposeChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ProposeChannel(ctx, req.(*ProposeChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_AcceptChannelProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptChannelProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).AcceptChannelProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_AcceptChannelProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).AcceptChannelProposal(ctx, req.(*AcceptChannelProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_RejectChannelProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectChannelProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).RejectChannelProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_RejectChannelProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).RejectChannelProposal(ctx, req.(*RejectChannelProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_RequestChannelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestChannelSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).RequestChannelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_RequestChannelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).RequestChannelSubscription(ctx, req.(*RequestChannelSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ApproveChannelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveChannelSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ApproveChannelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ApproveChannelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ApproveChannelSubscription(ctx, req.(*ApproveChannelSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_RejectChannelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectChannelSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).RejectChannelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_RejectChannelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).RejectChannelSubscription(ctx, req.(*RejectChannelSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_RequestPermissionChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPermissionChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).RequestPermissionChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_RequestPermissionChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).RequestPermissionChange(ctx, req.(*RequestPermissionChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ApprovePermissionChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePermissionChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ApprovePermissionChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ApprovePermissionChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ApprovePermissionChange(ctx, req.(*ApprovePermissionChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_RejectPermissionChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectPermissionChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).RejectPermissionChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_RejectPermissionChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).RejectPermissionChange(ctx, req.(*RejectPermissionChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_GetPermissionRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).GetPermissionRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_GetPermissionRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).GetPermissionRequests(ctx, req.(*GetPermissionRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_SendAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).SendAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_SendAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).SendAck(ctx, req.(*AckPacket))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelService_ServiceDesc is the grpc.ServiceDesc for ChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trusted_space.kernel.v1.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChannel",
			Handler:    _ChannelService_CreateChannel_Handler,
		},
		{
			MethodName: "CloseChannel",
			Handler:    _ChannelService_CloseChannel_Handler,
		},
		{
			MethodName: "NotifyChannelCreated",
			Handler:    _ChannelService_NotifyChannelCreated_Handler,
		},
		{
			MethodName: "GetChannelInfo",
			Handler:    _ChannelService_GetChannelInfo_Handler,
		},
		{
			MethodName: "ProposeChannel",
			Handler:    _ChannelService_ProposeChannel_Handler,
		},
		{
			MethodName: "AcceptChannelProposal",
			Handler:    _ChannelService_AcceptChannelProposal_Handler,
		},
		{
			MethodName: "RejectChannelProposal",
			Handler:    _ChannelService_RejectChannelProposal_Handler,
		},
		{
			MethodName: "RequestChannelSubscription",
			Handler:    _ChannelService_RequestChannelSubscription_Handler,
		},
		{
			MethodName: "ApproveChannelSubscription",
			Handler:    _ChannelService_ApproveChannelSubscription_Handler,
		},
		{
			MethodName: "RejectChannelSubscription",
			Handler:    _ChannelService_RejectChannelSubscription_Handler,
		},
		{
			MethodName: "RequestPermissionChange",
			Handler:    _ChannelService_RequestPermissionChange_Handler,
		},
		{
			MethodName: "ApprovePermissionChange",
			Handler:    _ChannelService_ApprovePermissionChange_Handler,
		},
		{
			MethodName: "RejectPermissionChange",
			Handler:    _ChannelService_RejectPermissionChange_Handler,
		},
		{
			MethodName: "GetPermissionRequests",
			Handler:    _ChannelService_GetPermissionRequests_Handler,
		},
		{
			MethodName: "SendAck",
			Handler:    _ChannelService_SendAck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _ChannelService_StreamData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeData",
			Handler:       _ChannelService_SubscribeData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WaitForChannelNotification",
			Handler:       _ChannelService_WaitForChannelNotification_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kernel/v1/channel.proto",
}
