// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: kernel/v1/evidence.proto

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EvidenceService_SubmitEvidence_FullMethodName          = "/trusted_space.kernel.v1.EvidenceService/SubmitEvidence"
	EvidenceService_QueryEvidence_FullMethodName           = "/trusted_space.kernel.v1.EvidenceService/QueryEvidence"
	EvidenceService_VerifyEvidenceSignature_FullMethodName = "/trusted_space.kernel.v1.EvidenceService/VerifyEvidenceSignature"
)

// EvidenceServiceClient is the client API for EvidenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------------------------------
// 存证溯源服务 (Evidence Service)
// ------------------------------------------------------------
// 实现全生命周期的数据安全管理与溯源
type EvidenceServiceClient interface {
	// 提交关键行为存证 (如：数据已发送、数据已接收、协议签署)
	SubmitEvidence(ctx context.Context, in *EvidenceRequest, opts ...grpc.CallOption) (*EvidenceResponse, error)
	// 查询存证记录 (用于审计)
	QueryEvidence(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// 验证存证记录的数字签名 (用于验证真实性)
	VerifyEvidenceSignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error)
}

type evidenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEvidenceServiceClient(cc grpc.ClientConnInterface) EvidenceServiceClient {
	return &evidenceServiceClient{cc}
}

func (c *evidenceServiceClient) SubmitEvidence(ctx context.Context, in *EvidenceRequest, opts ...grpc.CallOption) (*EvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvidenceResponse)
	err := c.cc.Invoke(ctx, EvidenceService_SubmitEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evidenceServiceClient) QueryEvidence(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, EvidenceService_QueryEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evidenceServiceClient) VerifyEvidenceSignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySignatureResponse)
	err := c.cc.Invoke(ctx, EvidenceService_VerifyEvidenceSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvidenceServiceServer is the server API for EvidenceService service.
// All implementations must embed UnimplementedEvidenceServiceServer
// for forward compatibility.
//
// ------------------------------------------------------------
// 存证溯源服务 (Evidence Service)
// ------------------------------------------------------------
// 实现全生命周期的数据安全管理与溯源
type EvidenceServiceServer interface {
	// 提交关键行为存证 (如：数据已发送、数据已接收、协议签署)
	SubmitEvidence(context.Context, *EvidenceRequest) (*EvidenceResponse, error)
	// 查询存证记录 (用于审计)
	QueryEvidence(context.Context, *QueryRequest) (*QueryResponse, error)
	// 验证存证记录的数字签名 (用于验证真实性)
	VerifyEvidenceSignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error)
	mustEmbedUnimplementedEvidenceServiceServer()
}

// UnimplementedEvidenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEvidenceServiceServer struct{}

func (UnimplementedEvidenceServiceServer) SubmitEvidence(context.Context, *EvidenceRequest) (*EvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitEvidence not implemented")
}
func (UnimplementedEvidenceServiceServer) QueryEvidence(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryEvidence not implemented")
}
func (UnimplementedEvidenceServiceServer) VerifyEvidenceSignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEvidenceSignature not implemented")
}
func (UnimplementedEvidenceServiceServer) mustEmbedUnimplementedEvidenceServiceServer() {}
func (UnimplementedEvidenceServiceServer) testEmbeddedByValue()                         {}

// UnsafeEvidenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvidenceServiceServer will
// result in compilation errors.
type UnsafeEvidenceServiceServer interface {
	mustEmbedUnimplementedEvidenceServiceServer()
}

func RegisterEvidenceServiceServer(s grpc.ServiceRegistrar, srv EvidenceServiceServer) {
	// If the following call panics, it indicates UnimplementedEvidenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EvidenceService_ServiceDesc, srv)
}

func _EvidenceService_SubmitEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceServiceServer).SubmitEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceService_SubmitEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceServiceServer).SubmitEvidence(ctx, req.(*EvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvidenceService_QueryEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceServiceServer).QueryEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceService_QueryEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceServiceServer).QueryEvidence(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvidenceService_VerifyEvidenceSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceServiceServer).VerifyEvidenceSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceService_VerifyEvidenceSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceServiceServer).VerifyEvidenceSignature(ctx, req.(*VerifySignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EvidenceService_ServiceDesc is the grpc.ServiceDesc for EvidenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvidenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trusted_space.kernel.v1.EvidenceService",
	HandlerType: (*EvidenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEvidence",
			Handler:    _EvidenceService_SubmitEvidence_Handler,
		},
		{
			MethodName: "QueryEvidence",
			Handler:    _EvidenceService_QueryEvidence_Handler,
		},
		{
			MethodName: "VerifyEvidenceSignature",
			Handler:    _EvidenceService_VerifyEvidenceSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kernel/v1/evidence.proto",
}
