// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: kernel/v1/evidence.proto

package kernelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // 类型: TRANSFER_START, TRANSFER_END, AUTH_FAIL
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	DataHash      string                 `protobuf:"bytes,4,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"` // 数据指纹，而非原始数据
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                                                                         // 行为不可抵赖签名
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceRequest) Reset() {
	*x = EvidenceRequest{}
	mi := &file_kernel_v1_evidence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceRequest) ProtoMessage() {}

func (x *EvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_evidence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceRequest.ProtoReflect.Descriptor instead.
func (*EvidenceRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_evidence_proto_rawDescGZIP(), []int{0}
}

func (x *EvidenceRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *EvidenceRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EvidenceRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *EvidenceRequest) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *EvidenceRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EvidenceRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EvidenceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvidenceTxId  string                 `protobuf:"bytes,1,opt,name=evidence_tx_id,json=evidenceTxId,proto3" json:"evidence_tx_id,omitempty"` // 存证交易号
	Committed     bool                   `protobuf:"varint,2,opt,name=committed,proto3" json:"committed,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceResponse) Reset() {
	*x = EvidenceResponse{}
	mi := &file_kernel_v1_evidence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceResponse) ProtoMessage() {}

func (x *EvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_evidence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceResponse.ProtoReflect.Descriptor instead.
func (*EvidenceResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_evidence_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceResponse) GetEvidenceTxId() string {
	if x != nil {
		return x.EvidenceTxId
	}
	return ""
}

func (x *EvidenceResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *EvidenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EvidenceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type QueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChannelId      string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ConnectorId    string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	FlowId         string                 `protobuf:"bytes,6,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // 业务流程ID，用于查询完整的数据流转过程
	StartTimestamp int64                  `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   int64                  `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_kernel_v1_evidence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_evidence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_evidence_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *QueryRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *QueryRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *QueryRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*EvidenceRecord      `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_kernel_v1_evidence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_evidence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_evidence_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetLogs() []*EvidenceRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type EvidenceRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EvidenceTxId    string                 `protobuf:"bytes,1,opt,name=evidence_tx_id,json=evidenceTxId,proto3" json:"evidence_tx_id,omitempty"`
	Evidence        *EvidenceRequest       `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	StoredTimestamp int64                  `protobuf:"varint,3,opt,name=stored_timestamp,json=storedTimestamp,proto3" json:"stored_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvidenceRecord) Reset() {
	*x = EvidenceRecord{}
	mi := &file_kernel_v1_evidence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceRecord) ProtoMessage() {}

func (x *EvidenceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_evidence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceRecord.ProtoReflect.Descriptor instead.
func (*EvidenceRecord) Descriptor() ([]byte, []int) {
	return file_kernel_v1_evidence_proto_rawDescGZIP(), []int{4}
}

func (x *EvidenceRecord) GetEvidenceTxId() string {
	if x != nil {
		return x.EvidenceTxId
	}
	return ""
}

func (x *EvidenceRecord) GetEvidence() *EvidenceRequest {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *EvidenceRecord) GetStoredTimestamp() int64 {
	if x != nil {
		return x.StoredTimestamp
	}
	return 0
}

type VerifySignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // 请求验证的连接器ID
	ConnectorId   string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 被验证的存证记录的连接器ID
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`       // 事件类型
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`       // 频道ID
	DataHash      string                 `protobuf:"bytes,5,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`          // 数据哈希
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                        // 要验证的签名
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignatureRequest) Reset() {
	*x = VerifySignatureRequest{}
	mi := &file_kernel_v1_evidence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureRequest) ProtoMessage() {}

func (x *VerifySignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_evidence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureRequest.ProtoReflect.Descriptor instead.
func (*VerifySignatureRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_evidence_proto_rawDescGZIP(), []int{5}
}

func (x *VerifySignatureRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *VerifySignatureRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *VerifySignatureRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *VerifySignatureRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *VerifySignatureRequest) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *VerifySignatureRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifySignatureRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type VerifySignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                             // 签名是否有效
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // 验证结果消息
	VerifiedAt    int64                  `protobuf:"varint,3,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"` // 验证时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignatureResponse) Reset() {
	*x = VerifySignatureResponse{}
	mi := &file_kernel_v1_evidence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureResponse) ProtoMessage() {}

func (x *VerifySignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_evidence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureResponse.ProtoReflect.Descriptor instead.
func (*VerifySignatureResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_evidence_proto_rawDescGZIP(), []int{6}
}

func (x *VerifySignatureResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifySignatureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifySignatureResponse) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

var File_kernel_v1_evidence_proto protoreflect.FileDescriptor

const file_kernel_v1_evidence_proto_rawDesc = "" +
	"\n" +
	"\x18kernel/v1/evidence.proto\x12\x17trusted_space.kernel.v1\"\xdc\x02\n" +
	"\x0fEvidenceRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tdata_hash\x18\x04 \x01(\tR\bdataHash\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12R\n" +
	"\bmetadata\x18\a \x03(\v26.trusted_space.kernel.v1.EvidenceRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x10EvidenceResponse\x12$\n" +
	"\x0eevidence_tx_id\x18\x01 \x01(\tR\fevidenceTxId\x12\x1c\n" +
	"\tcommitted\x18\x02 \x01(\bR\tcommitted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xcd\x01\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\x12\x17\n" +
	"\aflow_id\x18\x06 \x01(\tR\x06flowId\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\x03R\fendTimestamp\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"m\n" +
	"\rQueryResponse\x12;\n" +
	"\x04logs\x18\x01 \x03(\v2'.trusted_space.kernel.v1.EvidenceRecordR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa7\x01\n" +
	"\x0eEvidenceRecord\x12$\n" +
	"\x0eevidence_tx_id\x18\x01 \x01(\tR\fevidenceTxId\x12D\n" +
	"\bevidence\x18\x02 \x01(\v2(.trusted_space.kernel.v1.EvidenceRequestR\bevidence\x12)\n" +
	"\x10stored_timestamp\x18\x03 \x01(\x03R\x0fstoredTimestamp\"\xf5\x01\n" +
	"\x16VerifySignatureRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tdata_hash\x18\x05 \x01(\tR\bdataHash\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"j\n" +
	"\x17VerifySignatureResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vverified_at\x18\x03 \x01(\x03R\n" +
	"verifiedAt2\xd6\x02\n" +
	"\x0fEvidenceService\x12e\n" +
	"\x0eSubmitEvidence\x12(.trusted_space.kernel.v1.EvidenceRequest\x1a).trusted_space.kernel.v1.EvidenceResponse\x12^\n" +
	"\rQueryEvidence\x12%.trusted_space.kernel.v1.QueryRequest\x1a&.trusted_space.kernel.v1.QueryResponse\x12|\n" +
	"\x17VerifyEvidenceSignature\x12/.trusted_space.kernel.v1.VerifySignatureRequest\x1a0.trusted_space.kernel.v1.VerifySignatureResponseB1Z/github.com/trusted-space/kernel/api/v1;kernelv1b\x06proto3"

var (
	file_kernel_v1_evidence_proto_rawDescOnce sync.Once
	file_kernel_v1_evidence_proto_rawDescData []byte
)

func file_kernel_v1_evidence_proto_rawDescGZIP() []byte {
	file_kernel_v1_evidence_proto_rawDescOnce.Do(func() {
		file_kernel_v1_evidence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_v1_evidence_proto_rawDesc), len(file_kernel_v1_evidence_proto_rawDesc)))
	})
	return file_kernel_v1_evidence_proto_rawDescData
}

var file_kernel_v1_evidence_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kernel_v1_evidence_proto_goTypes = []any{
	(*EvidenceRequest)(nil),         // 0: trusted_space.kernel.v1.EvidenceRequest
	(*EvidenceResponse)(nil),        // 1: trusted_space.kernel.v1.EvidenceResponse
	(*QueryRequest)(nil),            // 2: trusted_space.kernel.v1.QueryRequest
	(*QueryResponse)(nil),           // 3: trusted_space.kernel.v1.QueryResponse
	(*EvidenceRecord)(nil),          // 4: trusted_space.kernel.v1.EvidenceRecord
	(*VerifySignatureRequest)(nil),  // 5: trusted_space.kernel.v1.VerifySignatureRequest
	(*VerifySignatureResponse)(nil), // 6: trusted_space.kernel.v1.VerifySignatureResponse
	nil,                             // 7: trusted_space.kernel.v1.EvidenceRequest.MetadataEntry
}
var file_kernel_v1_evidence_proto_depIdxs = []int32{
	7, // 0: trusted_space.kernel.v1.EvidenceRequest.metadata:type_name -> trusted_space.kernel.v1.EvidenceRequest.MetadataEntry
	4, // 1: trusted_space.kernel.v1.QueryResponse.logs:type_name -> trusted_space.kernel.v1.EvidenceRecord
	0, // 2: trusted_space.kernel.v1.EvidenceRecord.evidence:type_name -> trusted_space.kernel.v1.EvidenceRequest
	0, // 3: trusted_space.kernel.v1.EvidenceService.SubmitEvidence:input_type -> trusted_space.kernel.v1.EvidenceRequest
	2, // 4: trusted_space.kernel.v1.EvidenceService.QueryEvidence:input_type -> trusted_space.kernel.v1.QueryRequest
	5, // 5: trusted_space.kernel.v1.EvidenceService.VerifyEvidenceSignature:input_type -> trusted_space.kernel.v1.VerifySignatureRequest
	1, // 6: trusted_space.kernel.v1.EvidenceService.SubmitEvidence:output_type -> trusted_space.kernel.v1.EvidenceResponse
	3, // 7: trusted_space.kernel.v1.EvidenceService.QueryEvidence:output_type -> trusted_space.kernel.v1.QueryResponse
	6, // 8: trusted_space.kernel.v1.EvidenceService.VerifyEvidenceSignature:output_type -> trusted_space.kernel.v1.VerifySignatureResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kernel_v1_evidence_proto_init() }
func file_kernel_v1_evidence_proto_init() {
	if File_kernel_v1_evidence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_v1_evidence_proto_rawDesc), len(file_kernel_v1_evidence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernel_v1_evidence_proto_goTypes,
		DependencyIndexes: file_kernel_v1_evidence_proto_depIdxs,
		MessageInfos:      file_kernel_v1_evidence_proto_msgTypes,
	}.Build()
	File_kernel_v1_evidence_proto = out.File
	file_kernel_v1_evidence_proto_goTypes = nil
	file_kernel_v1_evidence_proto_depIdxs = nil
}
