// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: kernel/v1/identity.proto

package kernelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId      string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 连接器ID（需与证书CN匹配）
	EntityType       string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`    // 实体类型 (例如: 数据源, 算法节点)
	PublicKey        string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`       // 用于应用层加密的公钥
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Exposed          *bool                  `protobuf:"varint,5,opt,name=exposed,proto3,oneof" json:"exposed,omitempty"`                                      // 是否向其他内核公开自己的信息，默认为true（不设置时为true）
	DataCatalog      []string               `protobuf:"bytes,6,rep,name=data_catalog,json=dataCatalog,proto3" json:"data_catalog,omitempty"`                  // 数据类型/分类目录（如: ["传感器数据", "日志数据"]）（旧版，兼容）
	DataCatalogItems []*DataCatalogItem     `protobuf:"bytes,7,rep,name=data_catalog_items,json=dataCatalogItems,proto3" json:"data_catalog_items,omitempty"` // 结构化数据目录（新版，支持 exposed 字段）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *HandshakeRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *HandshakeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *HandshakeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandshakeRequest) GetExposed() bool {
	if x != nil && x.Exposed != nil {
		return *x.Exposed
	}
	return false
}

func (x *HandshakeRequest) GetDataCatalog() []string {
	if x != nil {
		return x.DataCatalog
	}
	return nil
}

func (x *HandshakeRequest) GetDataCatalogItems() []*DataCatalogItem {
	if x != nil {
		return x.DataCatalogItems
	}
	return nil
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // 临时会话令牌
	KernelVersion string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *HandshakeResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// ------------------------------------------------------------
// 目录服务消息定义
// ------------------------------------------------------------
type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // 请求者ID
	FilterType    string                 `protobuf:"bytes,2,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`    // 可选的实体类型过滤（为空则返回所有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *DiscoverRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []*ConnectorInfo       `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoverResponse) GetConnectors() []*ConnectorInfo {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *DiscoverResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 数据目录项结构
type DataCatalogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`            // 数据项唯一标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`        // 数据项名称
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`        // 数据类型
	Exposed       bool                   `protobuf:"varint,4,opt,name=exposed,proto3" json:"exposed,omitempty"` // 是否向外部内核展示，默认为 true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCatalogItem) Reset() {
	*x = DataCatalogItem{}
	mi := &file_kernel_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCatalogItem) ProtoMessage() {}

func (x *DataCatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCatalogItem.ProtoReflect.Descriptor instead.
func (*DataCatalogItem) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *DataCatalogItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataCatalogItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataCatalogItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataCatalogItem) GetExposed() bool {
	if x != nil {
		return x.Exposed
	}
	return false
}

type ConnectorInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId      string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	EntityType       string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	PublicKey        string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                                // active, inactive, offline, closed
	LastHeartbeat    int64                  `protobuf:"varint,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`            // Unix时间戳
	RegisteredAt     int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`               // Unix时间戳
	KernelId         string                 `protobuf:"bytes,7,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                            // 所属内核ID（为空表示本内核）
	DataCatalog      []string               `protobuf:"bytes,8,rep,name=data_catalog,json=dataCatalog,proto3" json:"data_catalog,omitempty"`                   // 数据类型/分类目录（旧版，兼容）
	Exposed          bool                   `protobuf:"varint,9,opt,name=exposed,proto3" json:"exposed,omitempty"`                                             // 是否向其他内核公开自己的信息
	DataCatalogItems []*DataCatalogItem     `protobuf:"bytes,10,rep,name=data_catalog_items,json=dataCatalogItems,proto3" json:"data_catalog_items,omitempty"` // 结构化数据目录（新版）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectorInfo) Reset() {
	*x = ConnectorInfo{}
	mi := &file_kernel_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorInfo) ProtoMessage() {}

func (x *ConnectorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorInfo.ProtoReflect.Descriptor instead.
func (*ConnectorInfo) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectorInfo) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *ConnectorInfo) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ConnectorInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ConnectorInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectorInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ConnectorInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *ConnectorInfo) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *ConnectorInfo) GetDataCatalog() []string {
	if x != nil {
		return x.DataCatalog
	}
	return nil
}

func (x *ConnectorInfo) GetExposed() bool {
	if x != nil {
		return x.Exposed
	}
	return false
}

func (x *ConnectorInfo) GetDataCatalogItems() []*DataCatalogItem {
	if x != nil {
		return x.DataCatalogItems
	}
	return nil
}

type GetConnectorInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequesterId    string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	ConnectorId    string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`            // 要查询的连接器ID
	TargetKernelId string                 `protobuf:"bytes,3,opt,name=target_kernel_id,json=targetKernelId,proto3" json:"target_kernel_id,omitempty"` // 目标内核ID（为空则查询本内核）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConnectorInfoRequest) Reset() {
	*x = GetConnectorInfoRequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorInfoRequest) ProtoMessage() {}

func (x *GetConnectorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorInfoRequest.ProtoReflect.Descriptor instead.
func (*GetConnectorInfoRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *GetConnectorInfoRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *GetConnectorInfoRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *GetConnectorInfoRequest) GetTargetKernelId() string {
	if x != nil {
		return x.TargetKernelId
	}
	return ""
}

type GetConnectorInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Connector     *ConnectorInfo         `protobuf:"bytes,2,opt,name=connector,proto3" json:"connector,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectorInfoResponse) Reset() {
	*x = GetConnectorInfoResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorInfoResponse) ProtoMessage() {}

func (x *GetConnectorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorInfoResponse.ProtoReflect.Descriptor instead.
func (*GetConnectorInfoResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *GetConnectorInfoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetConnectorInfoResponse) GetConnector() *ConnectorInfo {
	if x != nil {
		return x.Connector
	}
	return nil
}

func (x *GetConnectorInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ------------------------------------------------------------
// 跨内核连接器发现消息定义
// ------------------------------------------------------------
type CrossKernelDiscoverRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequesterId       string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`                     // 请求者ID
	RequesterKernelId string                 `protobuf:"bytes,2,opt,name=requester_kernel_id,json=requesterKernelId,proto3" json:"requester_kernel_id,omitempty"` // 请求者内核ID
	FilterType        string                 `protobuf:"bytes,3,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`                        // 可选的实体类型过滤
	TargetKernelId    string                 `protobuf:"bytes,4,opt,name=target_kernel_id,json=targetKernelId,proto3" json:"target_kernel_id,omitempty"`          // 目标内核ID（为空则查询所有已知内核）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CrossKernelDiscoverRequest) Reset() {
	*x = CrossKernelDiscoverRequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossKernelDiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossKernelDiscoverRequest) ProtoMessage() {}

func (x *CrossKernelDiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossKernelDiscoverRequest.ProtoReflect.Descriptor instead.
func (*CrossKernelDiscoverRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *CrossKernelDiscoverRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *CrossKernelDiscoverRequest) GetRequesterKernelId() string {
	if x != nil {
		return x.RequesterKernelId
	}
	return ""
}

func (x *CrossKernelDiscoverRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *CrossKernelDiscoverRequest) GetTargetKernelId() string {
	if x != nil {
		return x.TargetKernelId
	}
	return ""
}

type CrossKernelDiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []*ConnectorInfo       `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`                    // 连接器列表
	Kernels       []*KernelInfo          `protobuf:"bytes,2,rep,name=kernels,proto3" json:"kernels,omitempty"`                          // 内核信息列表
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总连接器数量
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossKernelDiscoverResponse) Reset() {
	*x = CrossKernelDiscoverResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossKernelDiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossKernelDiscoverResponse) ProtoMessage() {}

func (x *CrossKernelDiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossKernelDiscoverResponse.ProtoReflect.Descriptor instead.
func (*CrossKernelDiscoverResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *CrossKernelDiscoverResponse) GetConnectors() []*ConnectorInfo {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *CrossKernelDiscoverResponse) GetKernels() []*KernelInfo {
	if x != nil {
		return x.Kernels
	}
	return nil
}

func (x *CrossKernelDiscoverResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CrossKernelDiscoverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KernelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelId      string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                 // 内核ID
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                   // 内核地址
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                        // 内核端口
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                     // 内核状态: active, inactive, offline
	LastHeartbeat int64                  `protobuf:"varint,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // 最后心跳时间
	RegisteredAt  int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`    // 注册时间
	PublicKey     string                 `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`              // 内核公钥（用于安全通信）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelInfo) Reset() {
	*x = KernelInfo{}
	mi := &file_kernel_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelInfo) ProtoMessage() {}

func (x *KernelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelInfo.ProtoReflect.Descriptor instead.
func (*KernelInfo) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *KernelInfo) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *KernelInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KernelInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *KernelInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KernelInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *KernelInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *KernelInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// ------------------------------------------------------------
// 连接器状态管理消息定义
// ------------------------------------------------------------
type SetConnectorStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // 请求者ID（必须是连接器自己或管理员）
	ConnectorId   string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 要设置状态的连接器ID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // 目标状态：active, inactive, closed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectorStatusRequest) Reset() {
	*x = SetConnectorStatusRequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectorStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectorStatusRequest) ProtoMessage() {}

func (x *SetConnectorStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectorStatusRequest.ProtoReflect.Descriptor instead.
func (*SetConnectorStatusRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *SetConnectorStatusRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *SetConnectorStatusRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *SetConnectorStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetConnectorStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,3,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"` // 之前的状态
	CurrentStatus  string                 `protobuf:"bytes,4,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`    // 当前状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetConnectorStatusResponse) Reset() {
	*x = SetConnectorStatusResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectorStatusResponse) ProtoMessage() {}

func (x *SetConnectorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectorStatusResponse.ProtoReflect.Descriptor instead.
func (*SetConnectorStatusResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *SetConnectorStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetConnectorStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetConnectorStatusResponse) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

func (x *SetConnectorStatusResponse) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

// ------------------------------------------------------------
// 证书注册服务消息定义
// ------------------------------------------------------------
type RegisterConnectorRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId      string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`                // 连接器ID
	EntityType       string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                   // 实体类型
	PublicKey        string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                      // 用于应用层加密的公钥
	ConfigYaml       string                 `protobuf:"bytes,4,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`                   // 连接器配置（YAML格式）
	RegistrationCode string                 `protobuf:"bytes,5,opt,name=registration_code,json=registrationCode,proto3" json:"registration_code,omitempty"` // Bootstrap 一次性注册码（用于无证书首次注册）
	Timestamp        int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterConnectorRequest) Reset() {
	*x = RegisterConnectorRequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectorRequest) ProtoMessage() {}

func (x *RegisterConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectorRequest.ProtoReflect.Descriptor instead.
func (*RegisterConnectorRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterConnectorRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *RegisterConnectorRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *RegisterConnectorRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterConnectorRequest) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

func (x *RegisterConnectorRequest) GetRegistrationCode() string {
	if x != nil {
		return x.RegistrationCode
	}
	return ""
}

func (x *RegisterConnectorRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`                          // PEM格式的证书
	PrivateKey    []byte                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`          // PEM格式的私钥
	CaCertificate []byte                 `protobuf:"bytes,5,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"` // PEM格式的CA证书
	ConnectorId   string                 `protobuf:"bytes,6,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`       // 确认的连接器ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectorResponse) Reset() {
	*x = RegisterConnectorResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectorResponse) ProtoMessage() {}

func (x *RegisterConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectorResponse.ProtoReflect.Descriptor instead.
func (*RegisterConnectorResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterConnectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterConnectorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterConnectorResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterConnectorResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *RegisterConnectorResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *RegisterConnectorResponse) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

// ------------------------------------------------------------
// 内核 CA 交换消息定义
// ------------------------------------------------------------
type RegisterKernelCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelId      string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                // 内核ID
	CaCertificate []byte                 `protobuf:"bytes,2,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"` // PEM格式的中间CA证书
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKernelCARequest) Reset() {
	*x = RegisterKernelCARequest{}
	mi := &file_kernel_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKernelCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKernelCARequest) ProtoMessage() {}

func (x *RegisterKernelCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKernelCARequest.ProtoReflect.Descriptor instead.
func (*RegisterKernelCARequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterKernelCARequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *RegisterKernelCARequest) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *RegisterKernelCARequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterKernelCAResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PeerCaCertificate []byte                 `protobuf:"bytes,3,opt,name=peer_ca_certificate,json=peerCaCertificate,proto3" json:"peer_ca_certificate,omitempty"` // 对端返回的中间CA证书
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterKernelCAResponse) Reset() {
	*x = RegisterKernelCAResponse{}
	mi := &file_kernel_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKernelCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKernelCAResponse) ProtoMessage() {}

func (x *RegisterKernelCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKernelCAResponse.ProtoReflect.Descriptor instead.
func (*RegisterKernelCAResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterKernelCAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterKernelCAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterKernelCAResponse) GetPeerCaCertificate() []byte {
	if x != nil {
		return x.PeerCaCertificate
	}
	return nil
}

var File_kernel_v1_identity_proto protoreflect.FileDescriptor

const file_kernel_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x18kernel/v1/identity.proto\x12\x17trusted_space.kernel.v1\"\xb9\x02\n" +
	"\x10HandshakeRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\aexposed\x18\x05 \x01(\bH\x00R\aexposed\x88\x01\x01\x12!\n" +
	"\fdata_catalog\x18\x06 \x03(\tR\vdataCatalog\x12V\n" +
	"\x12data_catalog_items\x18\a \x03(\v2(.trusted_space.kernel.v1.DataCatalogItemR\x10dataCatalogItemsB\n" +
	"\n" +
	"\b_exposed\"\x93\x01\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"S\n" +
	"\x10HeartbeatRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"b\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"U\n" +
	"\x0fDiscoverRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1f\n" +
	"\vfilter_type\x18\x02 \x01(\tR\n" +
	"filterType\"{\n" +
	"\x10DiscoverResponse\x12F\n" +
	"\n" +
	"connectors\x18\x01 \x03(\v2&.trusted_space.kernel.v1.ConnectorInfoR\n" +
	"connectors\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"c\n" +
	"\x0fDataCatalogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aexposed\x18\x04 \x01(\bR\aexposed\"\x88\x03\n" +
	"\rConnectorInfo\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\x03R\rlastHeartbeat\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12\x1b\n" +
	"\tkernel_id\x18\a \x01(\tR\bkernelId\x12!\n" +
	"\fdata_catalog\x18\b \x03(\tR\vdataCatalog\x12\x18\n" +
	"\aexposed\x18\t \x01(\bR\aexposed\x12V\n" +
	"\x12data_catalog_items\x18\n" +
	" \x03(\v2(.trusted_space.kernel.v1.DataCatalogItemR\x10dataCatalogItems\"\x89\x01\n" +
	"\x17GetConnectorInfoRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\x12(\n" +
	"\x10target_kernel_id\x18\x03 \x01(\tR\x0etargetKernelId\"\x90\x01\n" +
	"\x18GetConnectorInfoResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12D\n" +
	"\tconnector\x18\x02 \x01(\v2&.trusted_space.kernel.v1.ConnectorInfoR\tconnector\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xba\x01\n" +
	"\x1aCrossKernelDiscoverRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12.\n" +
	"\x13requester_kernel_id\x18\x02 \x01(\tR\x11requesterKernelId\x12\x1f\n" +
	"\vfilter_type\x18\x03 \x01(\tR\n" +
	"filterType\x12(\n" +
	"\x10target_kernel_id\x18\x04 \x01(\tR\x0etargetKernelId\"\xdf\x01\n" +
	"\x1bCrossKernelDiscoverResponse\x12F\n" +
	"\n" +
	"connectors\x18\x01 \x03(\v2&.trusted_space.kernel.v1.ConnectorInfoR\n" +
	"connectors\x12=\n" +
	"\akernels\x18\x02 \x03(\v2#.trusted_space.kernel.v1.KernelInfoR\akernels\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xda\x01\n" +
	"\n" +
	"KernelInfo\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\x03R\rlastHeartbeat\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12\x1d\n" +
	"\n" +
	"public_key\x18\a \x01(\tR\tpublicKey\"y\n" +
	"\x19SetConnectorStatusRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xa0\x01\n" +
	"\x1aSetConnectorStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fprevious_status\x18\x03 \x01(\tR\x0epreviousStatus\x12%\n" +
	"\x0ecurrent_status\x18\x04 \x01(\tR\rcurrentStatus\"\xe9\x01\n" +
	"\x18RegisterConnectorRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vconfig_yaml\x18\x04 \x01(\tR\n" +
	"configYaml\x12+\n" +
	"\x11registration_code\x18\x05 \x01(\tR\x10registrationCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xdc\x01\n" +
	"\x19RegisterConnectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vcertificate\x18\x03 \x01(\fR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\fR\n" +
	"privateKey\x12%\n" +
	"\x0eca_certificate\x18\x05 \x01(\fR\rcaCertificate\x12!\n" +
	"\fconnector_id\x18\x06 \x01(\tR\vconnectorId\"{\n" +
	"\x17RegisterKernelCARequest\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12%\n" +
	"\x0eca_certificate\x18\x02 \x01(\fR\rcaCertificate\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"~\n" +
	"\x18RegisterKernelCAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x13peer_ca_certificate\x18\x03 \x01(\fR\x11peerCaCertificate2\xbe\a\n" +
	"\x0fIdentityService\x12b\n" +
	"\tHandshake\x12).trusted_space.kernel.v1.HandshakeRequest\x1a*.trusted_space.kernel.v1.HandshakeResponse\x12b\n" +
	"\tHeartbeat\x12).trusted_space.kernel.v1.HeartbeatRequest\x1a*.trusted_space.kernel.v1.HeartbeatResponse\x12i\n" +
	"\x12DiscoverConnectors\x12(.trusted_space.kernel.v1.DiscoverRequest\x1a).trusted_space.kernel.v1.DiscoverResponse\x12\x8a\x01\n" +
	"\x1dDiscoverCrossKernelConnectors\x123.trusted_space.kernel.v1.CrossKernelDiscoverRequest\x1a4.trusted_space.kernel.v1.CrossKernelDiscoverResponse\x12w\n" +
	"\x10GetConnectorInfo\x120.trusted_space.kernel.v1.GetConnectorInfoRequest\x1a1.trusted_space.kernel.v1.GetConnectorInfoResponse\x12}\n" +
	"\x12SetConnectorStatus\x122.trusted_space.kernel.v1.SetConnectorStatusRequest\x1a3.trusted_space.kernel.v1.SetConnectorStatusResponse\x12z\n" +
	"\x11RegisterConnector\x121.trusted_space.kernel.v1.RegisterConnectorRequest\x1a2.trusted_space.kernel.v1.RegisterConnectorResponse\x12w\n" +
	"\x10RegisterKernelCA\x120.trusted_space.kernel.v1.RegisterKernelCARequest\x1a1.trusted_space.kernel.v1.RegisterKernelCAResponseB1Z/github.com/trusted-space/kernel/api/v1;kernelv1b\x06proto3"

var (
	file_kernel_v1_identity_proto_rawDescOnce sync.Once
	file_kernel_v1_identity_proto_rawDescData []byte
)

func file_kernel_v1_identity_proto_rawDescGZIP() []byte {
	file_kernel_v1_identity_proto_rawDescOnce.Do(func() {
		file_kernel_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_v1_identity_proto_rawDesc), len(file_kernel_v1_identity_proto_rawDesc)))
	})
	return file_kernel_v1_identity_proto_rawDescData
}

var file_kernel_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_kernel_v1_identity_proto_goTypes = []any{
	(*HandshakeRequest)(nil),            // 0: trusted_space.kernel.v1.HandshakeRequest
	(*HandshakeResponse)(nil),           // 1: trusted_space.kernel.v1.HandshakeResponse
	(*HeartbeatRequest)(nil),            // 2: trusted_space.kernel.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 3: trusted_space.kernel.v1.HeartbeatResponse
	(*DiscoverRequest)(nil),             // 4: trusted_space.kernel.v1.DiscoverRequest
	(*DiscoverResponse)(nil),            // 5: trusted_space.kernel.v1.DiscoverResponse
	(*DataCatalogItem)(nil),             // 6: trusted_space.kernel.v1.DataCatalogItem
	(*ConnectorInfo)(nil),               // 7: trusted_space.kernel.v1.ConnectorInfo
	(*GetConnectorInfoRequest)(nil),     // 8: trusted_space.kernel.v1.GetConnectorInfoRequest
	(*GetConnectorInfoResponse)(nil),    // 9: trusted_space.kernel.v1.GetConnectorInfoResponse
	(*CrossKernelDiscoverRequest)(nil),  // 10: trusted_space.kernel.v1.CrossKernelDiscoverRequest
	(*CrossKernelDiscoverResponse)(nil), // 11: trusted_space.kernel.v1.CrossKernelDiscoverResponse
	(*KernelInfo)(nil),                  // 12: trusted_space.kernel.v1.KernelInfo
	(*SetConnectorStatusRequest)(nil),   // 13: trusted_space.kernel.v1.SetConnectorStatusRequest
	(*SetConnectorStatusResponse)(nil),  // 14: trusted_space.kernel.v1.SetConnectorStatusResponse
	(*RegisterConnectorRequest)(nil),    // 15: trusted_space.kernel.v1.RegisterConnectorRequest
	(*RegisterConnectorResponse)(nil),   // 16: trusted_space.kernel.v1.RegisterConnectorResponse
	(*RegisterKernelCARequest)(nil),     // 17: trusted_space.kernel.v1.RegisterKernelCARequest
	(*RegisterKernelCAResponse)(nil),    // 18: trusted_space.kernel.v1.RegisterKernelCAResponse
}
var file_kernel_v1_identity_proto_depIdxs = []int32{
	6,  // 0: trusted_space.kernel.v1.HandshakeRequest.data_catalog_items:type_name -> trusted_space.kernel.v1.DataCatalogItem
	7,  // 1: trusted_space.kernel.v1.DiscoverResponse.connectors:type_name -> trusted_space.kernel.v1.ConnectorInfo
	6,  // 2: trusted_space.kernel.v1.ConnectorInfo.data_catalog_items:type_name -> trusted_space.kernel.v1.DataCatalogItem
	7,  // 3: trusted_space.kernel.v1.GetConnectorInfoResponse.connector:type_name -> trusted_space.kernel.v1.ConnectorInfo
	7,  // 4: trusted_space.kernel.v1.CrossKernelDiscoverResponse.connectors:type_name -> trusted_space.kernel.v1.ConnectorInfo
	12, // 5: trusted_space.kernel.v1.CrossKernelDiscoverResponse.kernels:type_name -> trusted_space.kernel.v1.KernelInfo
	0,  // 6: trusted_space.kernel.v1.IdentityService.Handshake:input_type -> trusted_space.kernel.v1.HandshakeRequest
	2,  // 7: trusted_space.kernel.v1.IdentityService.Heartbeat:input_type -> trusted_space.kernel.v1.HeartbeatRequest
	4,  // 8: trusted_space.kernel.v1.IdentityService.DiscoverConnectors:input_type -> trusted_space.kernel.v1.DiscoverRequest
	10, // 9: trusted_space.kernel.v1.IdentityService.DiscoverCrossKernelConnectors:input_type -> trusted_space.kernel.v1.CrossKernelDiscoverRequest
	8,  // 10: trusted_space.kernel.v1.IdentityService.GetConnectorInfo:input_type -> trusted_space.kernel.v1.GetConnectorInfoRequest
	13, // 11: trusted_space.kernel.v1.IdentityService.SetConnectorStatus:input_type -> trusted_space.kernel.v1.SetConnectorStatusRequest
	15, // 12: trusted_space.kernel.v1.IdentityService.RegisterConnector:input_type -> trusted_space.kernel.v1.RegisterConnectorRequest
	17, // 13: trusted_space.kernel.v1.IdentityService.RegisterKernelCA:input_type -> trusted_space.kernel.v1.RegisterKernelCARequest
	1,  // 14: trusted_space.kernel.v1.IdentityService.Handshake:output_type -> trusted_space.kernel.v1.HandshakeResponse
	3,  // 15: trusted_space.kernel.v1.IdentityService.Heartbeat:output_type -> trusted_space.kernel.v1.HeartbeatResponse
	5,  // 16: trusted_space.kernel.v1.IdentityService.DiscoverConnectors:output_type -> trusted_space.kernel.v1.DiscoverResponse
	11, // 17: trusted_space.kernel.v1.IdentityService.DiscoverCrossKernelConnectors:output_type -> trusted_space.kernel.v1.CrossKernelDiscoverResponse
	9,  // 18: trusted_space.kernel.v1.IdentityService.GetConnectorInfo:output_type -> trusted_space.kernel.v1.GetConnectorInfoResponse
	14, // 19: trusted_space.kernel.v1.IdentityService.SetConnectorStatus:output_type -> trusted_space.kernel.v1.SetConnectorStatusResponse
	16, // 20: trusted_space.kernel.v1.IdentityService.RegisterConnector:output_type -> trusted_space.kernel.v1.RegisterConnectorResponse
	18, // 21: trusted_space.kernel.v1.IdentityService.RegisterKernelCA:output_type -> trusted_space.kernel.v1.RegisterKernelCAResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kernel_v1_identity_proto_init() }
func file_kernel_v1_identity_proto_init() {
	if File_kernel_v1_identity_proto != nil {
		return
	}
	file_kernel_v1_identity_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_v1_identity_proto_rawDesc), len(file_kernel_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernel_v1_identity_proto_goTypes,
		DependencyIndexes: file_kernel_v1_identity_proto_depIdxs,
		MessageInfos:      file_kernel_v1_identity_proto_msgTypes,
	}.Build()
	File_kernel_v1_identity_proto = out.File
	file_kernel_v1_identity_proto_goTypes = nil
	file_kernel_v1_identity_proto_depIdxs = nil
}
