// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: kernel/v1/identity.proto

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_Handshake_FullMethodName                     = "/trusted_space.kernel.v1.IdentityService/Handshake"
	IdentityService_Heartbeat_FullMethodName                     = "/trusted_space.kernel.v1.IdentityService/Heartbeat"
	IdentityService_DiscoverConnectors_FullMethodName            = "/trusted_space.kernel.v1.IdentityService/DiscoverConnectors"
	IdentityService_DiscoverCrossKernelConnectors_FullMethodName = "/trusted_space.kernel.v1.IdentityService/DiscoverCrossKernelConnectors"
	IdentityService_GetConnectorInfo_FullMethodName              = "/trusted_space.kernel.v1.IdentityService/GetConnectorInfo"
	IdentityService_SetConnectorStatus_FullMethodName            = "/trusted_space.kernel.v1.IdentityService/SetConnectorStatus"
	IdentityService_RegisterConnector_FullMethodName             = "/trusted_space.kernel.v1.IdentityService/RegisterConnector"
	IdentityService_RegisterKernelCA_FullMethodName              = "/trusted_space.kernel.v1.IdentityService/RegisterKernelCA"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------------------------------
// 身份与准入服务 (Identity Service)
// ------------------------------------------------------------
type IdentityServiceClient interface {
	// 连接器上线握手，注册自身能力，交换元信息
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// 心跳保活，维持在线状态
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 目录服务：发现空间中的其他连接器
	DiscoverConnectors(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	// 跨内核连接器发现
	DiscoverCrossKernelConnectors(ctx context.Context, in *CrossKernelDiscoverRequest, opts ...grpc.CallOption) (*CrossKernelDiscoverResponse, error)
	// 获取连接器详细信息
	GetConnectorInfo(ctx context.Context, in *GetConnectorInfoRequest, opts ...grpc.CallOption) (*GetConnectorInfoResponse, error)
	// 设置连接器状态（active, inactive, closed等）
	SetConnectorStatus(ctx context.Context, in *SetConnectorStatusRequest, opts ...grpc.CallOption) (*SetConnectorStatusResponse, error)
	// 证书注册服务：首次连接时动态申请证书
	RegisterConnector(ctx context.Context, in *RegisterConnectorRequest, opts ...grpc.CallOption) (*RegisterConnectorResponse, error)
	// 内核 CA 交换：内核间互联前，预先交换中间 CA 证书，
	// 使得后续 mTLS 握手时能够验证对方证书链
	RegisterKernelCA(ctx context.Context, in *RegisterKernelCARequest, opts ...grpc.CallOption) (*RegisterKernelCAResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, IdentityService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, IdentityService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DiscoverConnectors(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, IdentityService_DiscoverConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DiscoverCrossKernelConnectors(ctx context.Context, in *CrossKernelDiscoverRequest, opts ...grpc.CallOption) (*CrossKernelDiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrossKernelDiscoverResponse)
	err := c.cc.Invoke(ctx, IdentityService_DiscoverCrossKernelConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetConnectorInfo(ctx context.Context, in *GetConnectorInfoRequest, opts ...grpc.CallOption) (*GetConnectorInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectorInfoResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetConnectorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) SetConnectorStatus(ctx context.Context, in *SetConnectorStatusRequest, opts ...grpc.CallOption) (*SetConnectorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConnectorStatusResponse)
	err := c.cc.Invoke(ctx, IdentityService_SetConnectorStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RegisterConnector(ctx context.Context, in *RegisterConnectorRequest, opts ...grpc.CallOption) (*RegisterConnectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterConnectorResponse)
	err := c.cc.Invoke(ctx, IdentityService_RegisterConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RegisterKernelCA(ctx context.Context, in *RegisterKernelCARequest, opts ...grpc.CallOption) (*RegisterKernelCAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterKernelCAResponse)
	err := c.cc.Invoke(ctx, IdentityService_RegisterKernelCA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// ------------------------------------------------------------
// 身份与准入服务 (Identity Service)
// ------------------------------------------------------------
type IdentityServiceServer interface {
	// 连接器上线握手，注册自身能力，交换元信息
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// 心跳保活，维持在线状态
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 目录服务：发现空间中的其他连接器
	DiscoverConnectors(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	// 跨内核连接器发现
	DiscoverCrossKernelConnectors(context.Context, *CrossKernelDiscoverRequest) (*CrossKernelDiscoverResponse, error)
	// 获取连接器详细信息
	GetConnectorInfo(context.Context, *GetConnectorInfoRequest) (*GetConnectorInfoResponse, error)
	// 设置连接器状态（active, inactive, closed等）
	SetConnectorStatus(context.Context, *SetConnectorStatusRequest) (*SetConnectorStatusResponse, error)
	// 证书注册服务：首次连接时动态申请证书
	RegisterConnector(context.Context, *RegisterConnectorRequest) (*RegisterConnectorResponse, error)
	// 内核 CA 交换：内核间互联前，预先交换中间 CA 证书，
	// 使得后续 mTLS 握手时能够验证对方证书链
	RegisterKernelCA(context.Context, *RegisterKernelCARequest) (*RegisterKernelCAResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedIdentityServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedIdentityServiceServer) DiscoverConnectors(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverConnectors not implemented")
}
func (UnimplementedIdentityServiceServer) DiscoverCrossKernelConnectors(context.Context, *CrossKernelDiscoverRequest) (*CrossKernelDiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverCrossKernelConnectors not implemented")
}
func (UnimplementedIdentityServiceServer) GetConnectorInfo(context.Context, *GetConnectorInfoRequest) (*GetConnectorInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectorInfo not implemented")
}
func (UnimplementedIdentityServiceServer) SetConnectorStatus(context.Context, *SetConnectorStatusRequest) (*SetConnectorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConnectorStatus not implemented")
}
func (UnimplementedIdentityServiceServer) RegisterConnector(context.Context, *RegisterConnectorRequest) (*RegisterConnectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterConnector not implemented")
}
func (UnimplementedIdentityServiceServer) RegisterKernelCA(context.Context, *RegisterKernelCARequest) (*RegisterKernelCAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterKernelCA not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DiscoverConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DiscoverConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DiscoverConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DiscoverConnectors(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DiscoverCrossKernelConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossKernelDiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DiscoverCrossKernelConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DiscoverCrossKernelConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DiscoverCrossKernelConnectors(ctx, req.(*CrossKernelDiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetConnectorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectorInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetConnectorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetConnectorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetConnectorInfo(ctx, req.(*GetConnectorInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_SetConnectorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConnectorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SetConnectorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SetConnectorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SetConnectorStatus(ctx, req.(*SetConnectorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RegisterConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RegisterConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RegisterConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RegisterConnector(ctx, req.(*RegisterConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RegisterKernelCA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterKernelCARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RegisterKernelCA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RegisterKernelCA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RegisterKernelCA(ctx, req.(*RegisterKernelCARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trusted_space.kernel.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _IdentityService_Handshake_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _IdentityService_Heartbeat_Handler,
		},
		{
			MethodName: "DiscoverConnectors",
			Handler:    _IdentityService_DiscoverConnectors_Handler,
		},
		{
			MethodName: "DiscoverCrossKernelConnectors",
			Handler:    _IdentityService_DiscoverCrossKernelConnectors_Handler,
		},
		{
			MethodName: "GetConnectorInfo",
			Handler:    _IdentityService_GetConnectorInfo_Handler,
		},
		{
			MethodName: "SetConnectorStatus",
			Handler:    _IdentityService_SetConnectorStatus_Handler,
		},
		{
			MethodName: "RegisterConnector",
			Handler:    _IdentityService_RegisterConnector_Handler,
		},
		{
			MethodName: "RegisterKernelCA",
			Handler:    _IdentityService_RegisterKernelCA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kernel/v1/identity.proto",
}
