// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: kernel/v1/kernel.proto

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelService_RegisterKernel_FullMethodName              = "/trusted_space.kernel.v1.KernelService/RegisterKernel"
	KernelService_KernelHeartbeat_FullMethodName             = "/trusted_space.kernel.v1.KernelService/KernelHeartbeat"
	KernelService_DiscoverKernels_FullMethodName             = "/trusted_space.kernel.v1.KernelService/DiscoverKernels"
	KernelService_SyncKnownKernels_FullMethodName            = "/trusted_space.kernel.v1.KernelService/SyncKnownKernels"
	KernelService_CreateCrossKernelChannel_FullMethodName    = "/trusted_space.kernel.v1.KernelService/CreateCrossKernelChannel"
	KernelService_ForwardData_FullMethodName                 = "/trusted_space.kernel.v1.KernelService/ForwardData"
	KernelService_GetCrossKernelChannelInfo_FullMethodName   = "/trusted_space.kernel.v1.KernelService/GetCrossKernelChannelInfo"
	KernelService_SyncConnectorInfo_FullMethodName           = "/trusted_space.kernel.v1.KernelService/SyncConnectorInfo"
	KernelService_SyncPermissionRequest_FullMethodName       = "/trusted_space.kernel.v1.KernelService/SyncPermissionRequest"
	KernelService_GetRemotePermissionRequests_FullMethodName = "/trusted_space.kernel.v1.KernelService/GetRemotePermissionRequests"
	KernelService_HopEstablished_FullMethodName              = "/trusted_space.kernel.v1.KernelService/HopEstablished"
	KernelService_NotifyMultiHopApproved_FullMethodName      = "/trusted_space.kernel.v1.KernelService/NotifyMultiHopApproved"
	KernelService_ForwardAckNotification_FullMethodName      = "/trusted_space.kernel.v1.KernelService/ForwardAckNotification"
)

// KernelServiceClient is the client API for KernelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------------------------------
// 内核间通信服务 (Kernel Service)
// ------------------------------------------------------------
type KernelServiceClient interface {
	// 内核注册：新内核加入网络
	RegisterKernel(ctx context.Context, in *RegisterKernelRequest, opts ...grpc.CallOption) (*RegisterKernelResponse, error)
	// 内核心跳：维持内核间连接
	KernelHeartbeat(ctx context.Context, in *KernelHeartbeatRequest, opts ...grpc.CallOption) (*KernelHeartbeatResponse, error)
	// 内核发现：发现其他内核
	DiscoverKernels(ctx context.Context, in *DiscoverKernelsRequest, opts ...grpc.CallOption) (*DiscoverKernelsResponse, error)
	// 同步已知内核列表：让新连接的内核了解网络中其他内核
	SyncKnownKernels(ctx context.Context, in *SyncKnownKernelsRequest, opts ...grpc.CallOption) (*SyncKnownKernelsResponse, error)
	// 跨内核频道创建
	CreateCrossKernelChannel(ctx context.Context, in *CreateCrossKernelChannelRequest, opts ...grpc.CallOption) (*CreateCrossKernelChannelResponse, error)
	// 跨内核数据转发
	ForwardData(ctx context.Context, in *ForwardDataRequest, opts ...grpc.CallOption) (*ForwardDataResponse, error)
	// 跨内核频道信息查询
	GetCrossKernelChannelInfo(ctx context.Context, in *GetCrossKernelChannelInfoRequest, opts ...grpc.CallOption) (*GetCrossKernelChannelInfoResponse, error)
	// 同步连接器信息
	SyncConnectorInfo(ctx context.Context, in *SyncConnectorInfoRequest, opts ...grpc.CallOption) (*SyncConnectorInfoResponse, error)
	// 权限请求同步（跨内核）
	SyncPermissionRequest(ctx context.Context, in *SyncPermissionRequestRequest, opts ...grpc.CallOption) (*SyncPermissionRequestResponse, error)
	// 获取同步的权限请求
	GetRemotePermissionRequests(ctx context.Context, in *GetRemotePermissionRequestsRequest, opts ...grpc.CallOption) (*GetRemotePermissionRequestsResponse, error)
	// 多跳链路建立完成通知：当中间节点审批后并自动建立了下一跳连接时，
	// 通过此 RPC 通知发起方"该 hop 已由我代为完成"，发起方收到后自动建立对应连接。
	HopEstablished(ctx context.Context, in *HopEstablishedRequest, opts ...grpc.CallOption) (*HopEstablishedResponse, error)
	// 多跳链路审批通知：当目标内核审批了互联请求后，通过此 RPC 主动通知发起方，
	// 发起方收到后自动重试建立到该内核的连接，无需手动重新执行 connect-kernel --route。
	NotifyMultiHopApproved(ctx context.Context, in *NotifyMultiHopApprovedRequest, opts ...grpc.CallOption) (*NotifyMultiHopApprovedResponse, error)
	// ACK 强制转发通知：当 kernel-3 SendAck 时，通过此 RPC 通知 kernel-2 和 kernel-1
	// 让它们记录 ACK_RECEIVED 和 business_data_chain，同时让 kernel-2 继续转发给 kernel-1
	ForwardAckNotification(ctx context.Context, in *ForwardAckNotificationRequest, opts ...grpc.CallOption) (*ForwardAckNotificationResponse, error)
}

type kernelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelServiceClient(cc grpc.ClientConnInterface) KernelServiceClient {
	return &kernelServiceClient{cc}
}

func (c *kernelServiceClient) RegisterKernel(ctx context.Context, in *RegisterKernelRequest, opts ...grpc.CallOption) (*RegisterKernelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterKernelResponse)
	err := c.cc.Invoke(ctx, KernelService_RegisterKernel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) KernelHeartbeat(ctx context.Context, in *KernelHeartbeatRequest, opts ...grpc.CallOption) (*KernelHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KernelHeartbeatResponse)
	err := c.cc.Invoke(ctx, KernelService_KernelHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) DiscoverKernels(ctx context.Context, in *DiscoverKernelsRequest, opts ...grpc.CallOption) (*DiscoverKernelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverKernelsResponse)
	err := c.cc.Invoke(ctx, KernelService_DiscoverKernels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) SyncKnownKernels(ctx context.Context, in *SyncKnownKernelsRequest, opts ...grpc.CallOption) (*SyncKnownKernelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncKnownKernelsResponse)
	err := c.cc.Invoke(ctx, KernelService_SyncKnownKernels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) CreateCrossKernelChannel(ctx context.Context, in *CreateCrossKernelChannelRequest, opts ...grpc.CallOption) (*CreateCrossKernelChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCrossKernelChannelResponse)
	err := c.cc.Invoke(ctx, KernelService_CreateCrossKernelChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ForwardData(ctx context.Context, in *ForwardDataRequest, opts ...grpc.CallOption) (*ForwardDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardDataResponse)
	err := c.cc.Invoke(ctx, KernelService_ForwardData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) GetCrossKernelChannelInfo(ctx context.Context, in *GetCrossKernelChannelInfoRequest, opts ...grpc.CallOption) (*GetCrossKernelChannelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCrossKernelChannelInfoResponse)
	err := c.cc.Invoke(ctx, KernelService_GetCrossKernelChannelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) SyncConnectorInfo(ctx context.Context, in *SyncConnectorInfoRequest, opts ...grpc.CallOption) (*SyncConnectorInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncConnectorInfoResponse)
	err := c.cc.Invoke(ctx, KernelService_SyncConnectorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) SyncPermissionRequest(ctx context.Context, in *SyncPermissionRequestRequest, opts ...grpc.CallOption) (*SyncPermissionRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPermissionRequestResponse)
	err := c.cc.Invoke(ctx, KernelService_SyncPermissionRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) GetRemotePermissionRequests(ctx context.Context, in *GetRemotePermissionRequestsRequest, opts ...grpc.CallOption) (*GetRemotePermissionRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRemotePermissionRequestsResponse)
	err := c.cc.Invoke(ctx, KernelService_GetRemotePermissionRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) HopEstablished(ctx context.Context, in *HopEstablishedRequest, opts ...grpc.CallOption) (*HopEstablishedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HopEstablishedResponse)
	err := c.cc.Invoke(ctx, KernelService_HopEstablished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) NotifyMultiHopApproved(ctx context.Context, in *NotifyMultiHopApprovedRequest, opts ...grpc.CallOption) (*NotifyMultiHopApprovedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyMultiHopApprovedResponse)
	err := c.cc.Invoke(ctx, KernelService_NotifyMultiHopApproved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ForwardAckNotification(ctx context.Context, in *ForwardAckNotificationRequest, opts ...grpc.CallOption) (*ForwardAckNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardAckNotificationResponse)
	err := c.cc.Invoke(ctx, KernelService_ForwardAckNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelServiceServer is the server API for KernelService service.
// All implementations must embed UnimplementedKernelServiceServer
// for forward compatibility.
//
// ------------------------------------------------------------
// 内核间通信服务 (Kernel Service)
// ------------------------------------------------------------
type KernelServiceServer interface {
	// 内核注册：新内核加入网络
	RegisterKernel(context.Context, *RegisterKernelRequest) (*RegisterKernelResponse, error)
	// 内核心跳：维持内核间连接
	KernelHeartbeat(context.Context, *KernelHeartbeatRequest) (*KernelHeartbeatResponse, error)
	// 内核发现：发现其他内核
	DiscoverKernels(context.Context, *DiscoverKernelsRequest) (*DiscoverKernelsResponse, error)
	// 同步已知内核列表：让新连接的内核了解网络中其他内核
	SyncKnownKernels(context.Context, *SyncKnownKernelsRequest) (*SyncKnownKernelsResponse, error)
	// 跨内核频道创建
	CreateCrossKernelChannel(context.Context, *CreateCrossKernelChannelRequest) (*CreateCrossKernelChannelResponse, error)
	// 跨内核数据转发
	ForwardData(context.Context, *ForwardDataRequest) (*ForwardDataResponse, error)
	// 跨内核频道信息查询
	GetCrossKernelChannelInfo(context.Context, *GetCrossKernelChannelInfoRequest) (*GetCrossKernelChannelInfoResponse, error)
	// 同步连接器信息
	SyncConnectorInfo(context.Context, *SyncConnectorInfoRequest) (*SyncConnectorInfoResponse, error)
	// 权限请求同步（跨内核）
	SyncPermissionRequest(context.Context, *SyncPermissionRequestRequest) (*SyncPermissionRequestResponse, error)
	// 获取同步的权限请求
	GetRemotePermissionRequests(context.Context, *GetRemotePermissionRequestsRequest) (*GetRemotePermissionRequestsResponse, error)
	// 多跳链路建立完成通知：当中间节点审批后并自动建立了下一跳连接时，
	// 通过此 RPC 通知发起方"该 hop 已由我代为完成"，发起方收到后自动建立对应连接。
	HopEstablished(context.Context, *HopEstablishedRequest) (*HopEstablishedResponse, error)
	// 多跳链路审批通知：当目标内核审批了互联请求后，通过此 RPC 主动通知发起方，
	// 发起方收到后自动重试建立到该内核的连接，无需手动重新执行 connect-kernel --route。
	NotifyMultiHopApproved(context.Context, *NotifyMultiHopApprovedRequest) (*NotifyMultiHopApprovedResponse, error)
	// ACK 强制转发通知：当 kernel-3 SendAck 时，通过此 RPC 通知 kernel-2 和 kernel-1
	// 让它们记录 ACK_RECEIVED 和 business_data_chain，同时让 kernel-2 继续转发给 kernel-1
	ForwardAckNotification(context.Context, *ForwardAckNotificationRequest) (*ForwardAckNotificationResponse, error)
	mustEmbedUnimplementedKernelServiceServer()
}

// UnimplementedKernelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelServiceServer struct{}

func (UnimplementedKernelServiceServer) RegisterKernel(context.Context, *RegisterKernelRequest) (*RegisterKernelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterKernel not implemented")
}
func (UnimplementedKernelServiceServer) KernelHeartbeat(context.Context, *KernelHeartbeatRequest) (*KernelHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KernelHeartbeat not implemented")
}
func (UnimplementedKernelServiceServer) DiscoverKernels(context.Context, *DiscoverKernelsRequest) (*DiscoverKernelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverKernels not implemented")
}
func (UnimplementedKernelServiceServer) SyncKnownKernels(context.Context, *SyncKnownKernelsRequest) (*SyncKnownKernelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncKnownKernels not implemented")
}
func (UnimplementedKernelServiceServer) CreateCrossKernelChannel(context.Context, *CreateCrossKernelChannelRequest) (*CreateCrossKernelChannelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCrossKernelChannel not implemented")
}
func (UnimplementedKernelServiceServer) ForwardData(context.Context, *ForwardDataRequest) (*ForwardDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardData not implemented")
}
func (UnimplementedKernelServiceServer) GetCrossKernelChannelInfo(context.Context, *GetCrossKernelChannelInfoRequest) (*GetCrossKernelChannelInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCrossKernelChannelInfo not implemented")
}
func (UnimplementedKernelServiceServer) SyncConnectorInfo(context.Context, *SyncConnectorInfoRequest) (*SyncConnectorInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncConnectorInfo not implemented")
}
func (UnimplementedKernelServiceServer) SyncPermissionRequest(context.Context, *SyncPermissionRequestRequest) (*SyncPermissionRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPermissionRequest not implemented")
}
func (UnimplementedKernelServiceServer) GetRemotePermissionRequests(context.Context, *GetRemotePermissionRequestsRequest) (*GetRemotePermissionRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRemotePermissionRequests not implemented")
}
func (UnimplementedKernelServiceServer) HopEstablished(context.Context, *HopEstablishedRequest) (*HopEstablishedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HopEstablished not implemented")
}
func (UnimplementedKernelServiceServer) NotifyMultiHopApproved(context.Context, *NotifyMultiHopApprovedRequest) (*NotifyMultiHopApprovedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyMultiHopApproved not implemented")
}
func (UnimplementedKernelServiceServer) ForwardAckNotification(context.Context, *ForwardAckNotificationRequest) (*ForwardAckNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardAckNotification not implemented")
}
func (UnimplementedKernelServiceServer) mustEmbedUnimplementedKernelServiceServer() {}
func (UnimplementedKernelServiceServer) testEmbeddedByValue()                       {}

// UnsafeKernelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServiceServer will
// result in compilation errors.
type UnsafeKernelServiceServer interface {
	mustEmbedUnimplementedKernelServiceServer()
}

func RegisterKernelServiceServer(s grpc.ServiceRegistrar, srv KernelServiceServer) {
	// If the following call panics, it indicates UnimplementedKernelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelService_ServiceDesc, srv)
}

func _KernelService_RegisterKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).RegisterKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_RegisterKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).RegisterKernel(ctx, req.(*RegisterKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_KernelHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KernelHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).KernelHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_KernelHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).KernelHeartbeat(ctx, req.(*KernelHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_DiscoverKernels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverKernelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).DiscoverKernels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_DiscoverKernels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).DiscoverKernels(ctx, req.(*DiscoverKernelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_SyncKnownKernels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncKnownKernelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).SyncKnownKernels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_SyncKnownKernels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).SyncKnownKernels(ctx, req.(*SyncKnownKernelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_CreateCrossKernelChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCrossKernelChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).CreateCrossKernelChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_CreateCrossKernelChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).CreateCrossKernelChannel(ctx, req.(*CreateCrossKernelChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ForwardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ForwardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ForwardData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ForwardData(ctx, req.(*ForwardDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_GetCrossKernelChannelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrossKernelChannelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).GetCrossKernelChannelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_GetCrossKernelChannelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).GetCrossKernelChannelInfo(ctx, req.(*GetCrossKernelChannelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_SyncConnectorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncConnectorInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).SyncConnectorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_SyncConnectorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).SyncConnectorInfo(ctx, req.(*SyncConnectorInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_SyncPermissionRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPermissionRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).SyncPermissionRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_SyncPermissionRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).SyncPermissionRequest(ctx, req.(*SyncPermissionRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_GetRemotePermissionRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemotePermissionRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).GetRemotePermissionRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_GetRemotePermissionRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).GetRemotePermissionRequests(ctx, req.(*GetRemotePermissionRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_HopEstablished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HopEstablishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).HopEstablished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_HopEstablished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).HopEstablished(ctx, req.(*HopEstablishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_NotifyMultiHopApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyMultiHopApprovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).NotifyMultiHopApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_NotifyMultiHopApproved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).NotifyMultiHopApproved(ctx, req.(*NotifyMultiHopApprovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ForwardAckNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAckNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ForwardAckNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ForwardAckNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ForwardAckNotification(ctx, req.(*ForwardAckNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelService_ServiceDesc is the grpc.ServiceDesc for KernelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trusted_space.kernel.v1.KernelService",
	HandlerType: (*KernelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterKernel",
			Handler:    _KernelService_RegisterKernel_Handler,
		},
		{
			MethodName: "KernelHeartbeat",
			Handler:    _KernelService_KernelHeartbeat_Handler,
		},
		{
			MethodName: "DiscoverKernels",
			Handler:    _KernelService_DiscoverKernels_Handler,
		},
		{
			MethodName: "SyncKnownKernels",
			Handler:    _KernelService_SyncKnownKernels_Handler,
		},
		{
			MethodName: "CreateCrossKernelChannel",
			Handler:    _KernelService_CreateCrossKernelChannel_Handler,
		},
		{
			MethodName: "ForwardData",
			Handler:    _KernelService_ForwardData_Handler,
		},
		{
			MethodName: "GetCrossKernelChannelInfo",
			Handler:    _KernelService_GetCrossKernelChannelInfo_Handler,
		},
		{
			MethodName: "SyncConnectorInfo",
			Handler:    _KernelService_SyncConnectorInfo_Handler,
		},
		{
			MethodName: "SyncPermissionRequest",
			Handler:    _KernelService_SyncPermissionRequest_Handler,
		},
		{
			MethodName: "GetRemotePermissionRequests",
			Handler:    _KernelService_GetRemotePermissionRequests_Handler,
		},
		{
			MethodName: "HopEstablished",
			Handler:    _KernelService_HopEstablished_Handler,
		},
		{
			MethodName: "NotifyMultiHopApproved",
			Handler:    _KernelService_NotifyMultiHopApproved_Handler,
		},
		{
			MethodName: "ForwardAckNotification",
			Handler:    _KernelService_ForwardAckNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kernel/v1/kernel.proto",
}
