// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: kernel/v1/kernel.proto

package kernelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------
// 内核注册相关消息定义
// ------------------------------------------------------------
type RegisterKernelRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	KernelId              string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                // 内核ID
	Address               string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                  // 内核地址
	Port                  int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                       // 内核端口
	PublicKey             string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`             // 内核公钥
	CaCertificate         []byte                 `protobuf:"bytes,7,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"` // CA证书（PEM格式）
	Timestamp             int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsInterconnectRequest bool                   `protobuf:"varint,8,opt,name=is_interconnect_request,json=isInterconnectRequest,proto3" json:"is_interconnect_request,omitempty"` // 是否为互联请求
	IsInterconnectApprove bool                   `protobuf:"varint,9,opt,name=is_interconnect_approve,json=isInterconnectApprove,proto3" json:"is_interconnect_approve,omitempty"` // 是否为互联批准通知
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterKernelRequest) Reset() {
	*x = RegisterKernelRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKernelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKernelRequest) ProtoMessage() {}

func (x *RegisterKernelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKernelRequest.ProtoReflect.Descriptor instead.
func (*RegisterKernelRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterKernelRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *RegisterKernelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterKernelRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterKernelRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterKernelRequest) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *RegisterKernelRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegisterKernelRequest) GetIsInterconnectRequest() bool {
	if x != nil {
		return x.IsInterconnectRequest
	}
	return false
}

func (x *RegisterKernelRequest) GetIsInterconnectApprove() bool {
	if x != nil {
		return x.IsInterconnectApprove
	}
	return false
}

type RegisterKernelResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionToken      string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`                  // 会话令牌
	PeerCaCertificate []byte                 `protobuf:"bytes,5,opt,name=peer_ca_certificate,json=peerCaCertificate,proto3" json:"peer_ca_certificate,omitempty"` // 对等内核的CA证书
	KnownKernels      []*KernelInfo          `protobuf:"bytes,4,rep,name=known_kernels,json=knownKernels,proto3" json:"known_kernels,omitempty"`                  // 已知内核列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterKernelResponse) Reset() {
	*x = RegisterKernelResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKernelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKernelResponse) ProtoMessage() {}

func (x *RegisterKernelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKernelResponse.ProtoReflect.Descriptor instead.
func (*RegisterKernelResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterKernelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterKernelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterKernelResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterKernelResponse) GetPeerCaCertificate() []byte {
	if x != nil {
		return x.PeerCaCertificate
	}
	return nil
}

func (x *RegisterKernelResponse) GetKnownKernels() []*KernelInfo {
	if x != nil {
		return x.KnownKernels
	}
	return nil
}

// ------------------------------------------------------------
// 内核心跳相关消息定义
// ------------------------------------------------------------
type KernelHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelId      string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stats         map[string]int32       `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 统计信息：连接器数量、频道数量等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelHeartbeatRequest) Reset() {
	*x = KernelHeartbeatRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelHeartbeatRequest) ProtoMessage() {}

func (x *KernelHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*KernelHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{2}
}

func (x *KernelHeartbeatRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *KernelHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KernelHeartbeatRequest) GetStats() map[string]int32 {
	if x != nil {
		return x.Stats
	}
	return nil
}

type KernelHeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	Updates         []*KernelStatusUpdate  `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"` // 其他内核状态更新
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KernelHeartbeatResponse) Reset() {
	*x = KernelHeartbeatResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelHeartbeatResponse) ProtoMessage() {}

func (x *KernelHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*KernelHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{3}
}

func (x *KernelHeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *KernelHeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *KernelHeartbeatResponse) GetUpdates() []*KernelStatusUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type KernelStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelId      string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 内核状态变更
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelStatusUpdate) Reset() {
	*x = KernelStatusUpdate{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelStatusUpdate) ProtoMessage() {}

func (x *KernelStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelStatusUpdate.ProtoReflect.Descriptor instead.
func (*KernelStatusUpdate) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{4}
}

func (x *KernelStatusUpdate) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *KernelStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KernelStatusUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ------------------------------------------------------------
// 内核发现相关消息定义
// ------------------------------------------------------------
type DiscoverKernelsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequesterKernelId string                 `protobuf:"bytes,1,opt,name=requester_kernel_id,json=requesterKernelId,proto3" json:"requester_kernel_id,omitempty"`
	FilterStatus      string                 `protobuf:"bytes,2,opt,name=filter_status,json=filterStatus,proto3" json:"filter_status,omitempty"` // 状态过滤
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiscoverKernelsRequest) Reset() {
	*x = DiscoverKernelsRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverKernelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverKernelsRequest) ProtoMessage() {}

func (x *DiscoverKernelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverKernelsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverKernelsRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoverKernelsRequest) GetRequesterKernelId() string {
	if x != nil {
		return x.RequesterKernelId
	}
	return ""
}

func (x *DiscoverKernelsRequest) GetFilterStatus() string {
	if x != nil {
		return x.FilterStatus
	}
	return ""
}

type DiscoverKernelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kernels       []*KernelInfo          `protobuf:"bytes,1,rep,name=kernels,proto3" json:"kernels,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverKernelsResponse) Reset() {
	*x = DiscoverKernelsResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverKernelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverKernelsResponse) ProtoMessage() {}

func (x *DiscoverKernelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverKernelsResponse.ProtoReflect.Descriptor instead.
func (*DiscoverKernelsResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoverKernelsResponse) GetKernels() []*KernelInfo {
	if x != nil {
		return x.Kernels
	}
	return nil
}

func (x *DiscoverKernelsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ------------------------------------------------------------
// 同步已知内核相关消息定义
// ------------------------------------------------------------
type SyncKnownKernelsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceKernelId string                 `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 源内核ID
	KnownKernels   []*KernelInfo          `protobuf:"bytes,2,rep,name=known_kernels,json=knownKernels,proto3" json:"known_kernels,omitempty"`         // 源内核已知的内核列表
	SyncType       string                 `protobuf:"bytes,3,opt,name=sync_type,json=syncType,proto3" json:"sync_type,omitempty"`                     // 同步类型: full, incremental
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncKnownKernelsRequest) Reset() {
	*x = SyncKnownKernelsRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKnownKernelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKnownKernelsRequest) ProtoMessage() {}

func (x *SyncKnownKernelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKnownKernelsRequest.ProtoReflect.Descriptor instead.
func (*SyncKnownKernelsRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{7}
}

func (x *SyncKnownKernelsRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *SyncKnownKernelsRequest) GetKnownKernels() []*KernelInfo {
	if x != nil {
		return x.KnownKernels
	}
	return nil
}

func (x *SyncKnownKernelsRequest) GetSyncType() string {
	if x != nil {
		return x.SyncType
	}
	return ""
}

type SyncKnownKernelsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewlyKnownKernels []*KernelInfo          `protobuf:"bytes,3,rep,name=newly_known_kernels,json=newlyKnownKernels,proto3" json:"newly_known_kernels,omitempty"` // 对方之前不知道的内核
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncKnownKernelsResponse) Reset() {
	*x = SyncKnownKernelsResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKnownKernelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKnownKernelsResponse) ProtoMessage() {}

func (x *SyncKnownKernelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKnownKernelsResponse.ProtoReflect.Descriptor instead.
func (*SyncKnownKernelsResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{8}
}

func (x *SyncKnownKernelsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncKnownKernelsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncKnownKernelsResponse) GetNewlyKnownKernels() []*KernelInfo {
	if x != nil {
		return x.NewlyKnownKernels
	}
	return nil
}

// ------------------------------------------------------------
// 跨内核频道相关消息定义
// ------------------------------------------------------------
type CreateCrossKernelChannelRequest struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	CreatorKernelId    string                    `protobuf:"bytes,1,opt,name=creator_kernel_id,json=creatorKernelId,proto3" json:"creator_kernel_id,omitempty"`          // 创建者内核ID
	CreatorConnectorId string                    `protobuf:"bytes,2,opt,name=creator_connector_id,json=creatorConnectorId,proto3" json:"creator_connector_id,omitempty"` // 创建者连接器ID
	SenderIds          []*CrossKernelParticipant `protobuf:"bytes,3,rep,name=sender_ids,json=senderIds,proto3" json:"sender_ids,omitempty"`                              // 发送方列表（跨内核）
	ReceiverIds        []*CrossKernelParticipant `protobuf:"bytes,4,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`                        // 接收方列表（跨内核）
	DataTopic          string                    `protobuf:"bytes,5,opt,name=data_topic,json=dataTopic,proto3" json:"data_topic,omitempty"`                              // 数据主题
	Encrypted          bool                      `protobuf:"varint,6,opt,name=encrypted,proto3" json:"encrypted,omitempty"`                                              // 是否加密
	Reason             string                    `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`                                                     // 创建理由
	EvidenceConfig     *EvidenceConfig           `protobuf:"bytes,8,opt,name=evidence_config,json=evidenceConfig,proto3" json:"evidence_config,omitempty"`               // 存证配置
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCrossKernelChannelRequest) Reset() {
	*x = CreateCrossKernelChannelRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCrossKernelChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCrossKernelChannelRequest) ProtoMessage() {}

func (x *CreateCrossKernelChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCrossKernelChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateCrossKernelChannelRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCrossKernelChannelRequest) GetCreatorKernelId() string {
	if x != nil {
		return x.CreatorKernelId
	}
	return ""
}

func (x *CreateCrossKernelChannelRequest) GetCreatorConnectorId() string {
	if x != nil {
		return x.CreatorConnectorId
	}
	return ""
}

func (x *CreateCrossKernelChannelRequest) GetSenderIds() []*CrossKernelParticipant {
	if x != nil {
		return x.SenderIds
	}
	return nil
}

func (x *CreateCrossKernelChannelRequest) GetReceiverIds() []*CrossKernelParticipant {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *CreateCrossKernelChannelRequest) GetDataTopic() string {
	if x != nil {
		return x.DataTopic
	}
	return ""
}

func (x *CreateCrossKernelChannelRequest) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *CreateCrossKernelChannelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateCrossKernelChannelRequest) GetEvidenceConfig() *EvidenceConfig {
	if x != nil {
		return x.EvidenceConfig
	}
	return nil
}

type CrossKernelParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelId      string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`          // 内核ID
	ConnectorId   string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 连接器ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossKernelParticipant) Reset() {
	*x = CrossKernelParticipant{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossKernelParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossKernelParticipant) ProtoMessage() {}

func (x *CrossKernelParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossKernelParticipant.ProtoReflect.Descriptor instead.
func (*CrossKernelParticipant) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{10}
}

func (x *CrossKernelParticipant) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *CrossKernelParticipant) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

type CreateCrossKernelChannelResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Success                  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChannelId                string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // 全局唯一频道ID
	Message                  string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ParticipantConfirmations []string               `protobuf:"bytes,4,rep,name=participant_confirmations,json=participantConfirmations,proto3" json:"participant_confirmations,omitempty"` // 需要确认的参与者列表
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateCrossKernelChannelResponse) Reset() {
	*x = CreateCrossKernelChannelResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCrossKernelChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCrossKernelChannelResponse) ProtoMessage() {}

func (x *CreateCrossKernelChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCrossKernelChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateCrossKernelChannelResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCrossKernelChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCrossKernelChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CreateCrossKernelChannelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCrossKernelChannelResponse) GetParticipantConfirmations() []string {
	if x != nil {
		return x.ParticipantConfirmations
	}
	return nil
}

type ForwardDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceKernelId string                 `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 源内核ID
	TargetKernelId string                 `protobuf:"bytes,2,opt,name=target_kernel_id,json=targetKernelId,proto3" json:"target_kernel_id,omitempty"` // 目标内核ID
	ChannelId      string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                  // 频道ID
	DataPacket     *DataPacket            `protobuf:"bytes,4,opt,name=data_packet,json=dataPacket,proto3" json:"data_packet,omitempty"`               // 数据包
	IsFinal        bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`                       // 是否是最后一个数据包（流结束标志）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardDataRequest) Reset() {
	*x = ForwardDataRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDataRequest) ProtoMessage() {}

func (x *ForwardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDataRequest.ProtoReflect.Descriptor instead.
func (*ForwardDataRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{12}
}

func (x *ForwardDataRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *ForwardDataRequest) GetTargetKernelId() string {
	if x != nil {
		return x.TargetKernelId
	}
	return ""
}

func (x *ForwardDataRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ForwardDataRequest) GetDataPacket() *DataPacket {
	if x != nil {
		return x.DataPacket
	}
	return nil
}

func (x *ForwardDataRequest) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type ForwardDataResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ForwardedSequence int64                  `protobuf:"varint,3,opt,name=forwarded_sequence,json=forwardedSequence,proto3" json:"forwarded_sequence,omitempty"` // 转发后的序列号
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForwardDataResponse) Reset() {
	*x = ForwardDataResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDataResponse) ProtoMessage() {}

func (x *ForwardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDataResponse.ProtoReflect.Descriptor instead.
func (*ForwardDataResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{13}
}

func (x *ForwardDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForwardDataResponse) GetForwardedSequence() int64 {
	if x != nil {
		return x.ForwardedSequence
	}
	return 0
}

type GetCrossKernelChannelInfoRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequesterKernelId string                 `protobuf:"bytes,1,opt,name=requester_kernel_id,json=requesterKernelId,proto3" json:"requester_kernel_id,omitempty"`
	ChannelId         string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCrossKernelChannelInfoRequest) Reset() {
	*x = GetCrossKernelChannelInfoRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrossKernelChannelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrossKernelChannelInfoRequest) ProtoMessage() {}

func (x *GetCrossKernelChannelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrossKernelChannelInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCrossKernelChannelInfoRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{14}
}

func (x *GetCrossKernelChannelInfoRequest) GetRequesterKernelId() string {
	if x != nil {
		return x.RequesterKernelId
	}
	return ""
}

func (x *GetCrossKernelChannelInfoRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetCrossKernelChannelInfoResponse struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	Found              bool                      `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ChannelId          string                    `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CreatorKernelId    string                    `protobuf:"bytes,3,opt,name=creator_kernel_id,json=creatorKernelId,proto3" json:"creator_kernel_id,omitempty"`
	CreatorConnectorId string                    `protobuf:"bytes,4,opt,name=creator_connector_id,json=creatorConnectorId,proto3" json:"creator_connector_id,omitempty"`
	SenderIds          []*CrossKernelParticipant `protobuf:"bytes,5,rep,name=sender_ids,json=senderIds,proto3" json:"sender_ids,omitempty"`
	ReceiverIds        []*CrossKernelParticipant `protobuf:"bytes,6,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	DataTopic          string                    `protobuf:"bytes,7,opt,name=data_topic,json=dataTopic,proto3" json:"data_topic,omitempty"`
	Encrypted          bool                      `protobuf:"varint,8,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Status             string                    `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt          int64                     `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActivity       int64                     `protobuf:"varint,11,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	NegotiationStatus  ChannelNegotiationStatus  `protobuf:"varint,12,opt,name=negotiation_status,json=negotiationStatus,proto3,enum=trusted_space.kernel.v1.ChannelNegotiationStatus" json:"negotiation_status,omitempty"`
	Message            string                    `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCrossKernelChannelInfoResponse) Reset() {
	*x = GetCrossKernelChannelInfoResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrossKernelChannelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrossKernelChannelInfoResponse) ProtoMessage() {}

func (x *GetCrossKernelChannelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrossKernelChannelInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCrossKernelChannelInfoResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{15}
}

func (x *GetCrossKernelChannelInfoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetCrossKernelChannelInfoResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetCrossKernelChannelInfoResponse) GetCreatorKernelId() string {
	if x != nil {
		return x.CreatorKernelId
	}
	return ""
}

func (x *GetCrossKernelChannelInfoResponse) GetCreatorConnectorId() string {
	if x != nil {
		return x.CreatorConnectorId
	}
	return ""
}

func (x *GetCrossKernelChannelInfoResponse) GetSenderIds() []*CrossKernelParticipant {
	if x != nil {
		return x.SenderIds
	}
	return nil
}

func (x *GetCrossKernelChannelInfoResponse) GetReceiverIds() []*CrossKernelParticipant {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *GetCrossKernelChannelInfoResponse) GetDataTopic() string {
	if x != nil {
		return x.DataTopic
	}
	return ""
}

func (x *GetCrossKernelChannelInfoResponse) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *GetCrossKernelChannelInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCrossKernelChannelInfoResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetCrossKernelChannelInfoResponse) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *GetCrossKernelChannelInfoResponse) GetNegotiationStatus() ChannelNegotiationStatus {
	if x != nil {
		return x.NegotiationStatus
	}
	return ChannelNegotiationStatus_NEGOTIATION_STATUS_UNKNOWN
}

func (x *GetCrossKernelChannelInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ------------------------------------------------------------
// 连接器信息同步相关消息定义
// ------------------------------------------------------------
type SyncConnectorInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceKernelId string                 `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 源内核ID
	Connectors     []*ConnectorInfo       `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"`                                 // 要同步的连接器信息
	SyncType       string                 `protobuf:"bytes,3,opt,name=sync_type,json=syncType,proto3" json:"sync_type,omitempty"`                     // 同步类型: full, incremental, update
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncConnectorInfoRequest) Reset() {
	*x = SyncConnectorInfoRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConnectorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConnectorInfoRequest) ProtoMessage() {}

func (x *SyncConnectorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConnectorInfoRequest.ProtoReflect.Descriptor instead.
func (*SyncConnectorInfoRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{16}
}

func (x *SyncConnectorInfoRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *SyncConnectorInfoRequest) GetConnectors() []*ConnectorInfo {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *SyncConnectorInfoRequest) GetSyncType() string {
	if x != nil {
		return x.SyncType
	}
	return ""
}

type SyncConnectorInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SyncedCount   int32                  `protobuf:"varint,3,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"` // 同步的连接器数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConnectorInfoResponse) Reset() {
	*x = SyncConnectorInfoResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConnectorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConnectorInfoResponse) ProtoMessage() {}

func (x *SyncConnectorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConnectorInfoResponse.ProtoReflect.Descriptor instead.
func (*SyncConnectorInfoResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{17}
}

func (x *SyncConnectorInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncConnectorInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncConnectorInfoResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

// ------------------------------------------------------------
// 权限请求同步相关消息定义
// ------------------------------------------------------------
type SyncPermissionRequestRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	SourceKernelId string                   `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 源内核ID
	ChannelId      string                   `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                  // 频道ID
	Request        *PermissionChangeRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`                                       // 权限变更请求
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncPermissionRequestRequest) Reset() {
	*x = SyncPermissionRequestRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPermissionRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPermissionRequestRequest) ProtoMessage() {}

func (x *SyncPermissionRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPermissionRequestRequest.ProtoReflect.Descriptor instead.
func (*SyncPermissionRequestRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{18}
}

func (x *SyncPermissionRequestRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *SyncPermissionRequestRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SyncPermissionRequestRequest) GetRequest() *PermissionChangeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SyncPermissionRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPermissionRequestResponse) Reset() {
	*x = SyncPermissionRequestResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPermissionRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPermissionRequestResponse) ProtoMessage() {}

func (x *SyncPermissionRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPermissionRequestResponse.ProtoReflect.Descriptor instead.
func (*SyncPermissionRequestResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{19}
}

func (x *SyncPermissionRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncPermissionRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRemotePermissionRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // 请求者ID
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`       // 频道ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemotePermissionRequestsRequest) Reset() {
	*x = GetRemotePermissionRequestsRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemotePermissionRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemotePermissionRequestsRequest) ProtoMessage() {}

func (x *GetRemotePermissionRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemotePermissionRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetRemotePermissionRequestsRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{20}
}

func (x *GetRemotePermissionRequestsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *GetRemotePermissionRequestsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetRemotePermissionRequestsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Success       bool                       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Requests      []*PermissionChangeRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"` // 权限变更请求列表
	Message       string                     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemotePermissionRequestsResponse) Reset() {
	*x = GetRemotePermissionRequestsResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemotePermissionRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemotePermissionRequestsResponse) ProtoMessage() {}

func (x *GetRemotePermissionRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemotePermissionRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetRemotePermissionRequestsResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{21}
}

func (x *GetRemotePermissionRequestsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRemotePermissionRequestsResponse) GetRequests() []*PermissionChangeRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetRemotePermissionRequestsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ------------------------------------------------------------
// 多跳链路建立完成通知相关消息定义
// ------------------------------------------------------------
type HopEstablishedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceKernelId string                 `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 通知发送方内核ID（中间节点）
	HopId          string                 `protobuf:"bytes,2,opt,name=hop_id,json=hopId,proto3" json:"hop_id,omitempty"`                              // Hop 标识（如 "hop-2"）
	TargetKernelId string                 `protobuf:"bytes,3,opt,name=target_kernel_id,json=targetKernelId,proto3" json:"target_kernel_id,omitempty"` // 目标内核ID（本 hop 的终点）
	TargetAddress  string                 `protobuf:"bytes,4,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`      // 目标内核地址
	TargetPort     int32                  `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`              // 目标内核端口
	RouteName      string                 `protobuf:"bytes,6,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`                  // 所属路由名称
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HopEstablishedRequest) Reset() {
	*x = HopEstablishedRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HopEstablishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopEstablishedRequest) ProtoMessage() {}

func (x *HopEstablishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopEstablishedRequest.ProtoReflect.Descriptor instead.
func (*HopEstablishedRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{22}
}

func (x *HopEstablishedRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *HopEstablishedRequest) GetHopId() string {
	if x != nil {
		return x.HopId
	}
	return ""
}

func (x *HopEstablishedRequest) GetTargetKernelId() string {
	if x != nil {
		return x.TargetKernelId
	}
	return ""
}

func (x *HopEstablishedRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *HopEstablishedRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *HopEstablishedRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

type HopEstablishedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HopEstablishedResponse) Reset() {
	*x = HopEstablishedResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HopEstablishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopEstablishedResponse) ProtoMessage() {}

func (x *HopEstablishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopEstablishedResponse.ProtoReflect.Descriptor instead.
func (*HopEstablishedResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{23}
}

func (x *HopEstablishedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HopEstablishedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ------------------------------------------------------------
// 多跳链路审批通知相关消息定义
// ------------------------------------------------------------
type NotifyMultiHopApprovedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApprovedKernelId string                 `protobuf:"bytes,1,opt,name=approved_kernel_id,json=approvedKernelId,proto3" json:"approved_kernel_id,omitempty"` // 被批准的内核ID（发起方）
	ApproverKernelId string                 `protobuf:"bytes,2,opt,name=approver_kernel_id,json=approverKernelId,proto3" json:"approver_kernel_id,omitempty"` // 批准方内核ID
	RequestId        string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                        // 原始互联请求ID
	RouteName        string                 `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`                        // 所属路由名称（可选，用于路由追踪）
	HopIndex         int32                  `protobuf:"varint,5,opt,name=hop_index,json=hopIndex,proto3" json:"hop_index,omitempty"`                          // hop 序号（从1开始）
	HopTotal         int32                  `protobuf:"varint,6,opt,name=hop_total,json=hopTotal,proto3" json:"hop_total,omitempty"`                          // 总 hop 数
	ApprovedAt       int64                  `protobuf:"varint,7,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`                    // 批准时间戳
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotifyMultiHopApprovedRequest) Reset() {
	*x = NotifyMultiHopApprovedRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMultiHopApprovedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMultiHopApprovedRequest) ProtoMessage() {}

func (x *NotifyMultiHopApprovedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMultiHopApprovedRequest.ProtoReflect.Descriptor instead.
func (*NotifyMultiHopApprovedRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{24}
}

func (x *NotifyMultiHopApprovedRequest) GetApprovedKernelId() string {
	if x != nil {
		return x.ApprovedKernelId
	}
	return ""
}

func (x *NotifyMultiHopApprovedRequest) GetApproverKernelId() string {
	if x != nil {
		return x.ApproverKernelId
	}
	return ""
}

func (x *NotifyMultiHopApprovedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NotifyMultiHopApprovedRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *NotifyMultiHopApprovedRequest) GetHopIndex() int32 {
	if x != nil {
		return x.HopIndex
	}
	return 0
}

func (x *NotifyMultiHopApprovedRequest) GetHopTotal() int32 {
	if x != nil {
		return x.HopTotal
	}
	return 0
}

func (x *NotifyMultiHopApprovedRequest) GetApprovedAt() int64 {
	if x != nil {
		return x.ApprovedAt
	}
	return 0
}

type NotifyMultiHopApprovedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMultiHopApprovedResponse) Reset() {
	*x = NotifyMultiHopApprovedResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMultiHopApprovedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMultiHopApprovedResponse) ProtoMessage() {}

func (x *NotifyMultiHopApprovedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMultiHopApprovedResponse.ProtoReflect.Descriptor instead.
func (*NotifyMultiHopApprovedResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{25}
}

func (x *NotifyMultiHopApprovedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotifyMultiHopApprovedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ------------------------------------------------------------
// ACK 强制转发通知相关消息定义
// ------------------------------------------------------------
type ForwardAckNotificationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceKernelId     string                 `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"`           // 通知发送方内核ID（kernel-3）
	ChannelId          string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                            // 频道ID
	DataHash           string                 `protobuf:"bytes,3,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`                               // 被确认的数据包的 data_hash
	ConnectorSignature string                 `protobuf:"bytes,4,opt,name=connector_signature,json=connectorSignature,proto3" json:"connector_signature,omitempty"` // connector-X 对 data_hash 的签名（原始签名）
	KernelSignature    string                 `protobuf:"bytes,5,opt,name=kernel_signature,json=kernelSignature,proto3" json:"kernel_signature,omitempty"`          // kernel-3 对 ACK 的签名
	PrevSignature      string                 `protobuf:"bytes,6,opt,name=prev_signature,json=prevSignature,proto3" json:"prev_signature,omitempty"`                // kernel-3 对 data_hash 的签名（用于 kernel-2 RecordAck）
	FlowId             string                 `protobuf:"bytes,7,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`                                     // 业务流程ID
	OriginConnectorId  string                 `protobuf:"bytes,8,opt,name=origin_connector_id,json=originConnectorId,proto3" json:"origin_connector_id,omitempty"`  // 原始发送方 connector-A
	// 是否是最后一跳（kernel-1 收到时设为 true，不再转发）
	IsFinal       bool `protobuf:"varint,9,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardAckNotificationRequest) Reset() {
	*x = ForwardAckNotificationRequest{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardAckNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardAckNotificationRequest) ProtoMessage() {}

func (x *ForwardAckNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardAckNotificationRequest.ProtoReflect.Descriptor instead.
func (*ForwardAckNotificationRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{26}
}

func (x *ForwardAckNotificationRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetConnectorSignature() string {
	if x != nil {
		return x.ConnectorSignature
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetKernelSignature() string {
	if x != nil {
		return x.KernelSignature
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetPrevSignature() string {
	if x != nil {
		return x.PrevSignature
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetOriginConnectorId() string {
	if x != nil {
		return x.OriginConnectorId
	}
	return ""
}

func (x *ForwardAckNotificationRequest) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type ForwardAckNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardAckNotificationResponse) Reset() {
	*x = ForwardAckNotificationResponse{}
	mi := &file_kernel_v1_kernel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardAckNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardAckNotificationResponse) ProtoMessage() {}

func (x *ForwardAckNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_kernel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardAckNotificationResponse.ProtoReflect.Descriptor instead.
func (*ForwardAckNotificationResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_kernel_proto_rawDescGZIP(), []int{27}
}

func (x *ForwardAckNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardAckNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kernel_v1_kernel_proto protoreflect.FileDescriptor

const file_kernel_v1_kernel_proto_rawDesc = "" +
	"\n" +
	"\x16kernel/v1/kernel.proto\x12\x17trusted_space.kernel.v1\x1a\x18kernel/v1/identity.proto\x1a\x17kernel/v1/channel.proto\"\xb6\x02\n" +
	"\x15RegisterKernelRequest\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12%\n" +
	"\x0eca_certificate\x18\a \x01(\fR\rcaCertificate\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x126\n" +
	"\x17is_interconnect_request\x18\b \x01(\bR\x15isInterconnectRequest\x126\n" +
	"\x17is_interconnect_approve\x18\t \x01(\bR\x15isInterconnectApprove\"\xeb\x01\n" +
	"\x16RegisterKernelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12.\n" +
	"\x13peer_ca_certificate\x18\x05 \x01(\fR\x11peerCaCertificate\x12H\n" +
	"\rknown_kernels\x18\x04 \x03(\v2#.trusted_space.kernel.v1.KernelInfoR\fknownKernels\"\xdf\x01\n" +
	"\x16KernelHeartbeatRequest\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12P\n" +
	"\x05stats\x18\x03 \x03(\v2:.trusted_space.kernel.v1.KernelHeartbeatRequest.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xaf\x01\n" +
	"\x17KernelHeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\x12E\n" +
	"\aupdates\x18\x03 \x03(\v2+.trusted_space.kernel.v1.KernelStatusUpdateR\aupdates\"g\n" +
	"\x12KernelStatusUpdate\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"m\n" +
	"\x16DiscoverKernelsRequest\x12.\n" +
	"\x13requester_kernel_id\x18\x01 \x01(\tR\x11requesterKernelId\x12#\n" +
	"\rfilter_status\x18\x02 \x01(\tR\ffilterStatus\"y\n" +
	"\x17DiscoverKernelsResponse\x12=\n" +
	"\akernels\x18\x01 \x03(\v2#.trusted_space.kernel.v1.KernelInfoR\akernels\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xaa\x01\n" +
	"\x17SyncKnownKernelsRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12H\n" +
	"\rknown_kernels\x18\x02 \x03(\v2#.trusted_space.kernel.v1.KernelInfoR\fknownKernels\x12\x1b\n" +
	"\tsync_type\x18\x03 \x01(\tR\bsyncType\"\xa3\x01\n" +
	"\x18SyncKnownKernelsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12S\n" +
	"\x13newly_known_kernels\x18\x03 \x03(\v2#.trusted_space.kernel.v1.KernelInfoR\x11newlyKnownKernels\"\xca\x03\n" +
	"\x1fCreateCrossKernelChannelRequest\x12*\n" +
	"\x11creator_kernel_id\x18\x01 \x01(\tR\x0fcreatorKernelId\x120\n" +
	"\x14creator_connector_id\x18\x02 \x01(\tR\x12creatorConnectorId\x12N\n" +
	"\n" +
	"sender_ids\x18\x03 \x03(\v2/.trusted_space.kernel.v1.CrossKernelParticipantR\tsenderIds\x12R\n" +
	"\freceiver_ids\x18\x04 \x03(\v2/.trusted_space.kernel.v1.CrossKernelParticipantR\vreceiverIds\x12\x1d\n" +
	"\n" +
	"data_topic\x18\x05 \x01(\tR\tdataTopic\x12\x1c\n" +
	"\tencrypted\x18\x06 \x01(\bR\tencrypted\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12P\n" +
	"\x0fevidence_config\x18\b \x01(\v2'.trusted_space.kernel.v1.EvidenceConfigR\x0eevidenceConfig\"X\n" +
	"\x16CrossKernelParticipant\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\"\xb2\x01\n" +
	" CreateCrossKernelChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12;\n" +
	"\x19participant_confirmations\x18\x04 \x03(\tR\x18participantConfirmations\"\xe8\x01\n" +
	"\x12ForwardDataRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12(\n" +
	"\x10target_kernel_id\x18\x02 \x01(\tR\x0etargetKernelId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12D\n" +
	"\vdata_packet\x18\x04 \x01(\v2#.trusted_space.kernel.v1.DataPacketR\n" +
	"dataPacket\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\"x\n" +
	"\x13ForwardDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x12forwarded_sequence\x18\x03 \x01(\x03R\x11forwardedSequence\"q\n" +
	" GetCrossKernelChannelInfoRequest\x12.\n" +
	"\x13requester_kernel_id\x18\x01 \x01(\tR\x11requesterKernelId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\xef\x04\n" +
	"!GetCrossKernelChannelInfoResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12*\n" +
	"\x11creator_kernel_id\x18\x03 \x01(\tR\x0fcreatorKernelId\x120\n" +
	"\x14creator_connector_id\x18\x04 \x01(\tR\x12creatorConnectorId\x12N\n" +
	"\n" +
	"sender_ids\x18\x05 \x03(\v2/.trusted_space.kernel.v1.CrossKernelParticipantR\tsenderIds\x12R\n" +
	"\freceiver_ids\x18\x06 \x03(\v2/.trusted_space.kernel.v1.CrossKernelParticipantR\vreceiverIds\x12\x1d\n" +
	"\n" +
	"data_topic\x18\a \x01(\tR\tdataTopic\x12\x1c\n" +
	"\tencrypted\x18\b \x01(\bR\tencrypted\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12#\n" +
	"\rlast_activity\x18\v \x01(\x03R\flastActivity\x12`\n" +
	"\x12negotiation_status\x18\f \x01(\x0e21.trusted_space.kernel.v1.ChannelNegotiationStatusR\x11negotiationStatus\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\"\xa9\x01\n" +
	"\x18SyncConnectorInfoRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12F\n" +
	"\n" +
	"connectors\x18\x02 \x03(\v2&.trusted_space.kernel.v1.ConnectorInfoR\n" +
	"connectors\x12\x1b\n" +
	"\tsync_type\x18\x03 \x01(\tR\bsyncType\"r\n" +
	"\x19SyncConnectorInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fsynced_count\x18\x03 \x01(\x05R\vsyncedCount\"\xb3\x01\n" +
	"\x1cSyncPermissionRequestRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12J\n" +
	"\arequest\x18\x03 \x01(\v20.trusted_space.kernel.v1.PermissionChangeRequestR\arequest\"S\n" +
	"\x1dSyncPermissionRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\"GetRemotePermissionRequestsRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\xa7\x01\n" +
	"#GetRemotePermissionRequestsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12L\n" +
	"\brequests\x18\x02 \x03(\v20.trusted_space.kernel.v1.PermissionChangeRequestR\brequests\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe9\x01\n" +
	"\x15HopEstablishedRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12\x15\n" +
	"\x06hop_id\x18\x02 \x01(\tR\x05hopId\x12(\n" +
	"\x10target_kernel_id\x18\x03 \x01(\tR\x0etargetKernelId\x12%\n" +
	"\x0etarget_address\x18\x04 \x01(\tR\rtargetAddress\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\x05R\n" +
	"targetPort\x12\x1d\n" +
	"\n" +
	"route_name\x18\x06 \x01(\tR\trouteName\"L\n" +
	"\x16HopEstablishedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x02\n" +
	"\x1dNotifyMultiHopApprovedRequest\x12,\n" +
	"\x12approved_kernel_id\x18\x01 \x01(\tR\x10approvedKernelId\x12,\n" +
	"\x12approver_kernel_id\x18\x02 \x01(\tR\x10approverKernelId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x12\x1b\n" +
	"\thop_index\x18\x05 \x01(\x05R\bhopIndex\x12\x1b\n" +
	"\thop_total\x18\x06 \x01(\x05R\bhopTotal\x12\x1f\n" +
	"\vapproved_at\x18\a \x01(\x03R\n" +
	"approvedAt\"T\n" +
	"\x1eNotifyMultiHopApprovedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xec\x02\n" +
	"\x1dForwardAckNotificationRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tdata_hash\x18\x03 \x01(\tR\bdataHash\x12/\n" +
	"\x13connector_signature\x18\x04 \x01(\tR\x12connectorSignature\x12)\n" +
	"\x10kernel_signature\x18\x05 \x01(\tR\x0fkernelSignature\x12%\n" +
	"\x0eprev_signature\x18\x06 \x01(\tR\rprevSignature\x12\x17\n" +
	"\aflow_id\x18\a \x01(\tR\x06flowId\x12.\n" +
	"\x13origin_connector_id\x18\b \x01(\tR\x11originConnectorId\x12\x19\n" +
	"\bis_final\x18\t \x01(\bR\aisFinal\"T\n" +
	"\x1eForwardAckNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa3\r\n" +
	"\rKernelService\x12q\n" +
	"\x0eRegisterKernel\x12..trusted_space.kernel.v1.RegisterKernelRequest\x1a/.trusted_space.kernel.v1.RegisterKernelResponse\x12t\n" +
	"\x0fKernelHeartbeat\x12/.trusted_space.kernel.v1.KernelHeartbeatRequest\x1a0.trusted_space.kernel.v1.KernelHeartbeatResponse\x12t\n" +
	"\x0fDiscoverKernels\x12/.trusted_space.kernel.v1.DiscoverKernelsRequest\x1a0.trusted_space.kernel.v1.DiscoverKernelsResponse\x12w\n" +
	"\x10SyncKnownKernels\x120.trusted_space.kernel.v1.SyncKnownKernelsRequest\x1a1.trusted_space.kernel.v1.SyncKnownKernelsResponse\x12\x8f\x01\n" +
	"\x18CreateCrossKernelChannel\x128.trusted_space.kernel.v1.CreateCrossKernelChannelRequest\x1a9.trusted_space.kernel.v1.CreateCrossKernelChannelResponse\x12h\n" +
	"\vForwardData\x12+.trusted_space.kernel.v1.ForwardDataRequest\x1a,.trusted_space.kernel.v1.ForwardDataResponse\x12\x92\x01\n" +
	"\x19GetCrossKernelChannelInfo\x129.trusted_space.kernel.v1.GetCrossKernelChannelInfoRequest\x1a:.trusted_space.kernel.v1.GetCrossKernelChannelInfoResponse\x12z\n" +
	"\x11SyncConnectorInfo\x121.trusted_space.kernel.v1.SyncConnectorInfoRequest\x1a2.trusted_space.kernel.v1.SyncConnectorInfoResponse\x12\x86\x01\n" +
	"\x15SyncPermissionRequest\x125.trusted_space.kernel.v1.SyncPermissionRequestRequest\x1a6.trusted_space.kernel.v1.SyncPermissionRequestResponse\x12\x98\x01\n" +
	"\x1bGetRemotePermissionRequests\x12;.trusted_space.kernel.v1.GetRemotePermissionRequestsRequest\x1a<.trusted_space.kernel.v1.GetRemotePermissionRequestsResponse\x12q\n" +
	"\x0eHopEstablished\x12..trusted_space.kernel.v1.HopEstablishedRequest\x1a/.trusted_space.kernel.v1.HopEstablishedResponse\x12\x89\x01\n" +
	"\x16NotifyMultiHopApproved\x126.trusted_space.kernel.v1.NotifyMultiHopApprovedRequest\x1a7.trusted_space.kernel.v1.NotifyMultiHopApprovedResponse\x12\x89\x01\n" +
	"\x16ForwardAckNotification\x126.trusted_space.kernel.v1.ForwardAckNotificationRequest\x1a7.trusted_space.kernel.v1.ForwardAckNotificationResponseB1Z/github.com/trusted-space/kernel/api/v1;kernelv1b\x06proto3"

var (
	file_kernel_v1_kernel_proto_rawDescOnce sync.Once
	file_kernel_v1_kernel_proto_rawDescData []byte
)

func file_kernel_v1_kernel_proto_rawDescGZIP() []byte {
	file_kernel_v1_kernel_proto_rawDescOnce.Do(func() {
		file_kernel_v1_kernel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_v1_kernel_proto_rawDesc), len(file_kernel_v1_kernel_proto_rawDesc)))
	})
	return file_kernel_v1_kernel_proto_rawDescData
}

var file_kernel_v1_kernel_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_kernel_v1_kernel_proto_goTypes = []any{
	(*RegisterKernelRequest)(nil),               // 0: trusted_space.kernel.v1.RegisterKernelRequest
	(*RegisterKernelResponse)(nil),              // 1: trusted_space.kernel.v1.RegisterKernelResponse
	(*KernelHeartbeatRequest)(nil),              // 2: trusted_space.kernel.v1.KernelHeartbeatRequest
	(*KernelHeartbeatResponse)(nil),             // 3: trusted_space.kernel.v1.KernelHeartbeatResponse
	(*KernelStatusUpdate)(nil),                  // 4: trusted_space.kernel.v1.KernelStatusUpdate
	(*DiscoverKernelsRequest)(nil),              // 5: trusted_space.kernel.v1.DiscoverKernelsRequest
	(*DiscoverKernelsResponse)(nil),             // 6: trusted_space.kernel.v1.DiscoverKernelsResponse
	(*SyncKnownKernelsRequest)(nil),             // 7: trusted_space.kernel.v1.SyncKnownKernelsRequest
	(*SyncKnownKernelsResponse)(nil),            // 8: trusted_space.kernel.v1.SyncKnownKernelsResponse
	(*CreateCrossKernelChannelRequest)(nil),     // 9: trusted_space.kernel.v1.CreateCrossKernelChannelRequest
	(*CrossKernelParticipant)(nil),              // 10: trusted_space.kernel.v1.CrossKernelParticipant
	(*CreateCrossKernelChannelResponse)(nil),    // 11: trusted_space.kernel.v1.CreateCrossKernelChannelResponse
	(*ForwardDataRequest)(nil),                  // 12: trusted_space.kernel.v1.ForwardDataRequest
	(*ForwardDataResponse)(nil),                 // 13: trusted_space.kernel.v1.ForwardDataResponse
	(*GetCrossKernelChannelInfoRequest)(nil),    // 14: trusted_space.kernel.v1.GetCrossKernelChannelInfoRequest
	(*GetCrossKernelChannelInfoResponse)(nil),   // 15: trusted_space.kernel.v1.GetCrossKernelChannelInfoResponse
	(*SyncConnectorInfoRequest)(nil),            // 16: trusted_space.kernel.v1.SyncConnectorInfoRequest
	(*SyncConnectorInfoResponse)(nil),           // 17: trusted_space.kernel.v1.SyncConnectorInfoResponse
	(*SyncPermissionRequestRequest)(nil),        // 18: trusted_space.kernel.v1.SyncPermissionRequestRequest
	(*SyncPermissionRequestResponse)(nil),       // 19: trusted_space.kernel.v1.SyncPermissionRequestResponse
	(*GetRemotePermissionRequestsRequest)(nil),  // 20: trusted_space.kernel.v1.GetRemotePermissionRequestsRequest
	(*GetRemotePermissionRequestsResponse)(nil), // 21: trusted_space.kernel.v1.GetRemotePermissionRequestsResponse
	(*HopEstablishedRequest)(nil),               // 22: trusted_space.kernel.v1.HopEstablishedRequest
	(*HopEstablishedResponse)(nil),              // 23: trusted_space.kernel.v1.HopEstablishedResponse
	(*NotifyMultiHopApprovedRequest)(nil),       // 24: trusted_space.kernel.v1.NotifyMultiHopApprovedRequest
	(*NotifyMultiHopApprovedResponse)(nil),      // 25: trusted_space.kernel.v1.NotifyMultiHopApprovedResponse
	(*ForwardAckNotificationRequest)(nil),       // 26: trusted_space.kernel.v1.ForwardAckNotificationRequest
	(*ForwardAckNotificationResponse)(nil),      // 27: trusted_space.kernel.v1.ForwardAckNotificationResponse
	nil,                                         // 28: trusted_space.kernel.v1.KernelHeartbeatRequest.StatsEntry
	(*KernelInfo)(nil),                          // 29: trusted_space.kernel.v1.KernelInfo
	(*EvidenceConfig)(nil),                      // 30: trusted_space.kernel.v1.EvidenceConfig
	(*DataPacket)(nil),                          // 31: trusted_space.kernel.v1.DataPacket
	(ChannelNegotiationStatus)(0),               // 32: trusted_space.kernel.v1.ChannelNegotiationStatus
	(*ConnectorInfo)(nil),                       // 33: trusted_space.kernel.v1.ConnectorInfo
	(*PermissionChangeRequest)(nil),             // 34: trusted_space.kernel.v1.PermissionChangeRequest
}
var file_kernel_v1_kernel_proto_depIdxs = []int32{
	29, // 0: trusted_space.kernel.v1.RegisterKernelResponse.known_kernels:type_name -> trusted_space.kernel.v1.KernelInfo
	28, // 1: trusted_space.kernel.v1.KernelHeartbeatRequest.stats:type_name -> trusted_space.kernel.v1.KernelHeartbeatRequest.StatsEntry
	4,  // 2: trusted_space.kernel.v1.KernelHeartbeatResponse.updates:type_name -> trusted_space.kernel.v1.KernelStatusUpdate
	29, // 3: trusted_space.kernel.v1.DiscoverKernelsResponse.kernels:type_name -> trusted_space.kernel.v1.KernelInfo
	29, // 4: trusted_space.kernel.v1.SyncKnownKernelsRequest.known_kernels:type_name -> trusted_space.kernel.v1.KernelInfo
	29, // 5: trusted_space.kernel.v1.SyncKnownKernelsResponse.newly_known_kernels:type_name -> trusted_space.kernel.v1.KernelInfo
	10, // 6: trusted_space.kernel.v1.CreateCrossKernelChannelRequest.sender_ids:type_name -> trusted_space.kernel.v1.CrossKernelParticipant
	10, // 7: trusted_space.kernel.v1.CreateCrossKernelChannelRequest.receiver_ids:type_name -> trusted_space.kernel.v1.CrossKernelParticipant
	30, // 8: trusted_space.kernel.v1.CreateCrossKernelChannelRequest.evidence_config:type_name -> trusted_space.kernel.v1.EvidenceConfig
	31, // 9: trusted_space.kernel.v1.ForwardDataRequest.data_packet:type_name -> trusted_space.kernel.v1.DataPacket
	10, // 10: trusted_space.kernel.v1.GetCrossKernelChannelInfoResponse.sender_ids:type_name -> trusted_space.kernel.v1.CrossKernelParticipant
	10, // 11: trusted_space.kernel.v1.GetCrossKernelChannelInfoResponse.receiver_ids:type_name -> trusted_space.kernel.v1.CrossKernelParticipant
	32, // 12: trusted_space.kernel.v1.GetCrossKernelChannelInfoResponse.negotiation_status:type_name -> trusted_space.kernel.v1.ChannelNegotiationStatus
	33, // 13: trusted_space.kernel.v1.SyncConnectorInfoRequest.connectors:type_name -> trusted_space.kernel.v1.ConnectorInfo
	34, // 14: trusted_space.kernel.v1.SyncPermissionRequestRequest.request:type_name -> trusted_space.kernel.v1.PermissionChangeRequest
	34, // 15: trusted_space.kernel.v1.GetRemotePermissionRequestsResponse.requests:type_name -> trusted_space.kernel.v1.PermissionChangeRequest
	0,  // 16: trusted_space.kernel.v1.KernelService.RegisterKernel:input_type -> trusted_space.kernel.v1.RegisterKernelRequest
	2,  // 17: trusted_space.kernel.v1.KernelService.KernelHeartbeat:input_type -> trusted_space.kernel.v1.KernelHeartbeatRequest
	5,  // 18: trusted_space.kernel.v1.KernelService.DiscoverKernels:input_type -> trusted_space.kernel.v1.DiscoverKernelsRequest
	7,  // 19: trusted_space.kernel.v1.KernelService.SyncKnownKernels:input_type -> trusted_space.kernel.v1.SyncKnownKernelsRequest
	9,  // 20: trusted_space.kernel.v1.KernelService.CreateCrossKernelChannel:input_type -> trusted_space.kernel.v1.CreateCrossKernelChannelRequest
	12, // 21: trusted_space.kernel.v1.KernelService.ForwardData:input_type -> trusted_space.kernel.v1.ForwardDataRequest
	14, // 22: trusted_space.kernel.v1.KernelService.GetCrossKernelChannelInfo:input_type -> trusted_space.kernel.v1.GetCrossKernelChannelInfoRequest
	16, // 23: trusted_space.kernel.v1.KernelService.SyncConnectorInfo:input_type -> trusted_space.kernel.v1.SyncConnectorInfoRequest
	18, // 24: trusted_space.kernel.v1.KernelService.SyncPermissionRequest:input_type -> trusted_space.kernel.v1.SyncPermissionRequestRequest
	20, // 25: trusted_space.kernel.v1.KernelService.GetRemotePermissionRequests:input_type -> trusted_space.kernel.v1.GetRemotePermissionRequestsRequest
	22, // 26: trusted_space.kernel.v1.KernelService.HopEstablished:input_type -> trusted_space.kernel.v1.HopEstablishedRequest
	24, // 27: trusted_space.kernel.v1.KernelService.NotifyMultiHopApproved:input_type -> trusted_space.kernel.v1.NotifyMultiHopApprovedRequest
	26, // 28: trusted_space.kernel.v1.KernelService.ForwardAckNotification:input_type -> trusted_space.kernel.v1.ForwardAckNotificationRequest
	1,  // 29: trusted_space.kernel.v1.KernelService.RegisterKernel:output_type -> trusted_space.kernel.v1.RegisterKernelResponse
	3,  // 30: trusted_space.kernel.v1.KernelService.KernelHeartbeat:output_type -> trusted_space.kernel.v1.KernelHeartbeatResponse
	6,  // 31: trusted_space.kernel.v1.KernelService.DiscoverKernels:output_type -> trusted_space.kernel.v1.DiscoverKernelsResponse
	8,  // 32: trusted_space.kernel.v1.KernelService.SyncKnownKernels:output_type -> trusted_space.kernel.v1.SyncKnownKernelsResponse
	11, // 33: trusted_space.kernel.v1.KernelService.CreateCrossKernelChannel:output_type -> trusted_space.kernel.v1.CreateCrossKernelChannelResponse
	13, // 34: trusted_space.kernel.v1.KernelService.ForwardData:output_type -> trusted_space.kernel.v1.ForwardDataResponse
	15, // 35: trusted_space.kernel.v1.KernelService.GetCrossKernelChannelInfo:output_type -> trusted_space.kernel.v1.GetCrossKernelChannelInfoResponse
	17, // 36: trusted_space.kernel.v1.KernelService.SyncConnectorInfo:output_type -> trusted_space.kernel.v1.SyncConnectorInfoResponse
	19, // 37: trusted_space.kernel.v1.KernelService.SyncPermissionRequest:output_type -> trusted_space.kernel.v1.SyncPermissionRequestResponse
	21, // 38: trusted_space.kernel.v1.KernelService.GetRemotePermissionRequests:output_type -> trusted_space.kernel.v1.GetRemotePermissionRequestsResponse
	23, // 39: trusted_space.kernel.v1.KernelService.HopEstablished:output_type -> trusted_space.kernel.v1.HopEstablishedResponse
	25, // 40: trusted_space.kernel.v1.KernelService.NotifyMultiHopApproved:output_type -> trusted_space.kernel.v1.NotifyMultiHopApprovedResponse
	27, // 41: trusted_space.kernel.v1.KernelService.ForwardAckNotification:output_type -> trusted_space.kernel.v1.ForwardAckNotificationResponse
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_kernel_v1_kernel_proto_init() }
func file_kernel_v1_kernel_proto_init() {
	if File_kernel_v1_kernel_proto != nil {
		return
	}
	file_kernel_v1_identity_proto_init()
	file_kernel_v1_channel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_v1_kernel_proto_rawDesc), len(file_kernel_v1_kernel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernel_v1_kernel_proto_goTypes,
		DependencyIndexes: file_kernel_v1_kernel_proto_depIdxs,
		MessageInfos:      file_kernel_v1_kernel_proto_msgTypes,
	}.Build()
	File_kernel_v1_kernel_proto = out.File
	file_kernel_v1_kernel_proto_goTypes = nil
	file_kernel_v1_kernel_proto_depIdxs = nil
}
