// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: kernel/v1/operator_peer.proto

package kernelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// P2P协议消息类型
type P2PMessageType int32

const (
	// 握手
	P2PMessageType_P2P_HANDSHAKE     P2PMessageType = 0 // 握手请求
	P2PMessageType_P2P_HANDSHAKE_ACK P2PMessageType = 1 // 握手响应
	// 连接器同步
	P2PMessageType_P2P_SYNC_CONNECTORS     P2PMessageType = 10 // 同步在线连接器列表
	P2PMessageType_P2P_SYNC_CONNECTORS_ACK P2PMessageType = 11 // 同步响应
	// 消息转发
	P2PMessageType_P2P_RELAY_MESSAGE     P2PMessageType = 20 // 转发连接器消息
	P2PMessageType_P2P_RELAY_MESSAGE_ACK P2PMessageType = 21 // 转发确认
	// 心跳
	P2PMessageType_P2P_HEARTBEAT     P2PMessageType = 30 // P2P心跳
	P2PMessageType_P2P_HEARTBEAT_ACK P2PMessageType = 31 // 心跳响应
	// 断开
	P2PMessageType_P2P_DISCONNECT P2PMessageType = 40 // 通知对方断开连接
)

// Enum value maps for P2PMessageType.
var (
	P2PMessageType_name = map[int32]string{
		0:  "P2P_HANDSHAKE",
		1:  "P2P_HANDSHAKE_ACK",
		10: "P2P_SYNC_CONNECTORS",
		11: "P2P_SYNC_CONNECTORS_ACK",
		20: "P2P_RELAY_MESSAGE",
		21: "P2P_RELAY_MESSAGE_ACK",
		30: "P2P_HEARTBEAT",
		31: "P2P_HEARTBEAT_ACK",
		40: "P2P_DISCONNECT",
	}
	P2PMessageType_value = map[string]int32{
		"P2P_HANDSHAKE":           0,
		"P2P_HANDSHAKE_ACK":       1,
		"P2P_SYNC_CONNECTORS":     10,
		"P2P_SYNC_CONNECTORS_ACK": 11,
		"P2P_RELAY_MESSAGE":       20,
		"P2P_RELAY_MESSAGE_ACK":   21,
		"P2P_HEARTBEAT":           30,
		"P2P_HEARTBEAT_ACK":       31,
		"P2P_DISCONNECT":          40,
	}
)

func (x P2PMessageType) Enum() *P2PMessageType {
	p := new(P2PMessageType)
	*p = x
	return p
}

func (x P2PMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (P2PMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_kernel_v1_operator_peer_proto_enumTypes[0].Descriptor()
}

func (P2PMessageType) Type() protoreflect.EnumType {
	return &file_kernel_v1_operator_peer_proto_enumTypes[0]
}

func (x P2PMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use P2PMessageType.Descriptor instead.
func (P2PMessageType) EnumDescriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{0}
}

// P2P数据包（用于TCP传输）
type P2PPacket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           P2PMessageType         `protobuf:"varint,1,opt,name=type,proto3,enum=trusted_space.kernel.v1.P2PMessageType" json:"type,omitempty"` // 消息类型
	SourceKernelId string                 `protobuf:"bytes,2,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"`  // 源内核ID
	TargetKernelId string                 `protobuf:"bytes,3,opt,name=target_kernel_id,json=targetKernelId,proto3" json:"target_kernel_id,omitempty"`  // 目标内核ID（用于路由，可为空表示广播）
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                        // 消息载荷（序列化后的消息）
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // 时间戳
	TraceId        string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                         // 追踪ID（用于日志和调试）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *P2PPacket) Reset() {
	*x = P2PPacket{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PPacket) ProtoMessage() {}

func (x *P2PPacket) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PPacket.ProtoReflect.Descriptor instead.
func (*P2PPacket) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{0}
}

func (x *P2PPacket) GetType() P2PMessageType {
	if x != nil {
		return x.Type
	}
	return P2PMessageType_P2P_HANDSHAKE
}

func (x *P2PPacket) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *P2PPacket) GetTargetKernelId() string {
	if x != nil {
		return x.TargetKernelId
	}
	return ""
}

func (x *P2PPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *P2PPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P2PPacket) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ================================================================
// 握手消息
// ================================================================
type P2PHandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelId      string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                // 本内核ID
	KernelAddress string                 `protobuf:"bytes,2,opt,name=kernel_address,json=kernelAddress,proto3" json:"kernel_address,omitempty"` // 本内核地址（用于反向连接）
	KernelPort    int32                  `protobuf:"varint,3,opt,name=kernel_port,json=kernelPort,proto3" json:"kernel_port,omitempty"`         // 本内核端口
	PeerPort      int32                  `protobuf:"varint,4,opt,name=peer_port,json=peerPort,proto3" json:"peer_port,omitempty"`               // 本运维方P2P端口
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                                  // 协议版本
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PHandshakeRequest) Reset() {
	*x = P2PHandshakeRequest{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PHandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PHandshakeRequest) ProtoMessage() {}

func (x *P2PHandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PHandshakeRequest.ProtoReflect.Descriptor instead.
func (*P2PHandshakeRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{1}
}

func (x *P2PHandshakeRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *P2PHandshakeRequest) GetKernelAddress() string {
	if x != nil {
		return x.KernelAddress
	}
	return ""
}

func (x *P2PHandshakeRequest) GetKernelPort() int32 {
	if x != nil {
		return x.KernelPort
	}
	return 0
}

func (x *P2PHandshakeRequest) GetPeerPort() int32 {
	if x != nil {
		return x.PeerPort
	}
	return 0
}

func (x *P2PHandshakeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *P2PHandshakeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type P2PHandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	KernelId      string                 `protobuf:"bytes,3,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"` // 对方内核ID
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                   // 协议版本
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PHandshakeResponse) Reset() {
	*x = P2PHandshakeResponse{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PHandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PHandshakeResponse) ProtoMessage() {}

func (x *P2PHandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PHandshakeResponse.ProtoReflect.Descriptor instead.
func (*P2PHandshakeResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{2}
}

func (x *P2PHandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *P2PHandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *P2PHandshakeResponse) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *P2PHandshakeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *P2PHandshakeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ================================================================
// 连接器同步消息
// ================================================================
type P2PSyncConnectorsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceKernelId string                 `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 源内核ID
	Connectors     []*ConnectorOnlineInfo `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"`                                 // 本内核在线连接器列表
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // 同步时间戳
	TraceId        string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                        // 追踪ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *P2PSyncConnectorsRequest) Reset() {
	*x = P2PSyncConnectorsRequest{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PSyncConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PSyncConnectorsRequest) ProtoMessage() {}

func (x *P2PSyncConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PSyncConnectorsRequest.ProtoReflect.Descriptor instead.
func (*P2PSyncConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{3}
}

func (x *P2PSyncConnectorsRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *P2PSyncConnectorsRequest) GetConnectors() []*ConnectorOnlineInfo {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *P2PSyncConnectorsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P2PSyncConnectorsRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type P2PSyncConnectorsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RemoteConnectors []*ConnectorOnlineInfo `protobuf:"bytes,3,rep,name=remote_connectors,json=remoteConnectors,proto3" json:"remote_connectors,omitempty"` // 对方的在线连接器
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *P2PSyncConnectorsResponse) Reset() {
	*x = P2PSyncConnectorsResponse{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PSyncConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PSyncConnectorsResponse) ProtoMessage() {}

func (x *P2PSyncConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PSyncConnectorsResponse.ProtoReflect.Descriptor instead.
func (*P2PSyncConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{4}
}

func (x *P2PSyncConnectorsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *P2PSyncConnectorsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *P2PSyncConnectorsResponse) GetRemoteConnectors() []*ConnectorOnlineInfo {
	if x != nil {
		return x.RemoteConnectors
	}
	return nil
}

func (x *P2PSyncConnectorsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ================================================================
// 消息转发消息
// ================================================================
type P2PRelayMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                  // 消息ID
	SenderId       string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                     // 发送者连接器ID
	SenderKernelId string                 `protobuf:"bytes,3,opt,name=sender_kernel_id,json=senderKernelId,proto3" json:"sender_kernel_id,omitempty"` // 发送者所属内核ID
	ReceiverId     string                 `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`               // 接收者连接器ID
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                                       // 消息载荷
	Timestamp      int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // 时间戳
	FlowId         string                 `protobuf:"bytes,7,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`                           // 业务流程ID（可选）
	TraceId        string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                        // 追踪ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *P2PRelayMessageRequest) Reset() {
	*x = P2PRelayMessageRequest{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PRelayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PRelayMessageRequest) ProtoMessage() {}

func (x *P2PRelayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PRelayMessageRequest.ProtoReflect.Descriptor instead.
func (*P2PRelayMessageRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{5}
}

func (x *P2PRelayMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *P2PRelayMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *P2PRelayMessageRequest) GetSenderKernelId() string {
	if x != nil {
		return x.SenderKernelId
	}
	return ""
}

func (x *P2PRelayMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *P2PRelayMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *P2PRelayMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P2PRelayMessageRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *P2PRelayMessageRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type P2PRelayMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`        // 消息ID
	DeliveredAt   int64                  `protobuf:"varint,4,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"` // 投递时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PRelayMessageResponse) Reset() {
	*x = P2PRelayMessageResponse{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PRelayMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PRelayMessageResponse) ProtoMessage() {}

func (x *P2PRelayMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PRelayMessageResponse.ProtoReflect.Descriptor instead.
func (*P2PRelayMessageResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{6}
}

func (x *P2PRelayMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *P2PRelayMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *P2PRelayMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *P2PRelayMessageResponse) GetDeliveredAt() int64 {
	if x != nil {
		return x.DeliveredAt
	}
	return 0
}

// ================================================================
// 心跳消息
// ================================================================
type P2PHeartbeatRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	KernelId            string                 `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                                   // 本内核ID
	Timestamp           int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                // 时间戳
	ConnectedConnectors int32                  `protobuf:"varint,3,opt,name=connected_connectors,json=connectedConnectors,proto3" json:"connected_connectors,omitempty"` // 本内核连接器数量
	ActivePeers         int32                  `protobuf:"varint,4,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`                         // 当前活跃的P2P连接数
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *P2PHeartbeatRequest) Reset() {
	*x = P2PHeartbeatRequest{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PHeartbeatRequest) ProtoMessage() {}

func (x *P2PHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*P2PHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{7}
}

func (x *P2PHeartbeatRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *P2PHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P2PHeartbeatRequest) GetConnectedConnectors() int32 {
	if x != nil {
		return x.ConnectedConnectors
	}
	return 0
}

func (x *P2PHeartbeatRequest) GetActivePeers() int32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

type P2PHeartbeatResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	KernelId            string                 `protobuf:"bytes,2,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"` // 对方内核ID
	Timestamp           int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 服务器时间
	ConnectedConnectors int32                  `protobuf:"varint,4,opt,name=connected_connectors,json=connectedConnectors,proto3" json:"connected_connectors,omitempty"`
	ActivePeers         int32                  `protobuf:"varint,5,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *P2PHeartbeatResponse) Reset() {
	*x = P2PHeartbeatResponse{}
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PHeartbeatResponse) ProtoMessage() {}

func (x *P2PHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_operator_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*P2PHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_operator_peer_proto_rawDescGZIP(), []int{8}
}

func (x *P2PHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *P2PHeartbeatResponse) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *P2PHeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P2PHeartbeatResponse) GetConnectedConnectors() int32 {
	if x != nil {
		return x.ConnectedConnectors
	}
	return 0
}

func (x *P2PHeartbeatResponse) GetActivePeers() int32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

var File_kernel_v1_operator_peer_proto protoreflect.FileDescriptor

const file_kernel_v1_operator_peer_proto_rawDesc = "" +
	"\n" +
	"\x1dkernel/v1/operator_peer.proto\x12\x17trusted_space.kernel.v1\x1a\x18kernel/v1/tempchat.proto\"\xef\x01\n" +
	"\tP2PPacket\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.trusted_space.kernel.v1.P2PMessageTypeR\x04type\x12(\n" +
	"\x10source_kernel_id\x18\x02 \x01(\tR\x0esourceKernelId\x12(\n" +
	"\x10target_kernel_id\x18\x03 \x01(\tR\x0etargetKernelId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"\xcf\x01\n" +
	"\x13P2PHandshakeRequest\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12%\n" +
	"\x0ekernel_address\x18\x02 \x01(\tR\rkernelAddress\x12\x1f\n" +
	"\vkernel_port\x18\x03 \x01(\x05R\n" +
	"kernelPort\x12\x1b\n" +
	"\tpeer_port\x18\x04 \x01(\x05R\bpeerPort\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x9f\x01\n" +
	"\x14P2PHandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tkernel_id\x18\x03 \x01(\tR\bkernelId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xcb\x01\n" +
	"\x18P2PSyncConnectorsRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12L\n" +
	"\n" +
	"connectors\x18\x02 \x03(\v2,.trusted_space.kernel.v1.ConnectorOnlineInfoR\n" +
	"connectors\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"\xc8\x01\n" +
	"\x19P2PSyncConnectorsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Y\n" +
	"\x11remote_connectors\x18\x03 \x03(\v2,.trusted_space.kernel.v1.ConnectorOnlineInfoR\x10remoteConnectors\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x8b\x02\n" +
	"\x16P2PRelayMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12(\n" +
	"\x10sender_kernel_id\x18\x03 \x01(\tR\x0esenderKernelId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\aflow_id\x18\a \x01(\tR\x06flowId\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\"\x8f\x01\n" +
	"\x17P2PRelayMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12!\n" +
	"\fdelivered_at\x18\x04 \x01(\x03R\vdeliveredAt\"\xa6\x01\n" +
	"\x13P2PHeartbeatRequest\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x121\n" +
	"\x14connected_connectors\x18\x03 \x01(\x05R\x13connectedConnectors\x12!\n" +
	"\factive_peers\x18\x04 \x01(\x05R\vactivePeers\"\xc1\x01\n" +
	"\x14P2PHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tkernel_id\x18\x02 \x01(\tR\bkernelId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x121\n" +
	"\x14connected_connectors\x18\x04 \x01(\x05R\x13connectedConnectors\x12!\n" +
	"\factive_peers\x18\x05 \x01(\x05R\vactivePeers*\xe0\x01\n" +
	"\x0eP2PMessageType\x12\x11\n" +
	"\rP2P_HANDSHAKE\x10\x00\x12\x15\n" +
	"\x11P2P_HANDSHAKE_ACK\x10\x01\x12\x17\n" +
	"\x13P2P_SYNC_CONNECTORS\x10\n" +
	"\x12\x1b\n" +
	"\x17P2P_SYNC_CONNECTORS_ACK\x10\v\x12\x15\n" +
	"\x11P2P_RELAY_MESSAGE\x10\x14\x12\x19\n" +
	"\x15P2P_RELAY_MESSAGE_ACK\x10\x15\x12\x11\n" +
	"\rP2P_HEARTBEAT\x10\x1e\x12\x15\n" +
	"\x11P2P_HEARTBEAT_ACK\x10\x1f\x12\x12\n" +
	"\x0eP2P_DISCONNECT\x10(B1Z/github.com/trusted-space/kernel/api/v1;kernelv1b\x06proto3"

var (
	file_kernel_v1_operator_peer_proto_rawDescOnce sync.Once
	file_kernel_v1_operator_peer_proto_rawDescData []byte
)

func file_kernel_v1_operator_peer_proto_rawDescGZIP() []byte {
	file_kernel_v1_operator_peer_proto_rawDescOnce.Do(func() {
		file_kernel_v1_operator_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_v1_operator_peer_proto_rawDesc), len(file_kernel_v1_operator_peer_proto_rawDesc)))
	})
	return file_kernel_v1_operator_peer_proto_rawDescData
}

var file_kernel_v1_operator_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kernel_v1_operator_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kernel_v1_operator_peer_proto_goTypes = []any{
	(P2PMessageType)(0),               // 0: trusted_space.kernel.v1.P2PMessageType
	(*P2PPacket)(nil),                 // 1: trusted_space.kernel.v1.P2PPacket
	(*P2PHandshakeRequest)(nil),       // 2: trusted_space.kernel.v1.P2PHandshakeRequest
	(*P2PHandshakeResponse)(nil),      // 3: trusted_space.kernel.v1.P2PHandshakeResponse
	(*P2PSyncConnectorsRequest)(nil),  // 4: trusted_space.kernel.v1.P2PSyncConnectorsRequest
	(*P2PSyncConnectorsResponse)(nil), // 5: trusted_space.kernel.v1.P2PSyncConnectorsResponse
	(*P2PRelayMessageRequest)(nil),    // 6: trusted_space.kernel.v1.P2PRelayMessageRequest
	(*P2PRelayMessageResponse)(nil),   // 7: trusted_space.kernel.v1.P2PRelayMessageResponse
	(*P2PHeartbeatRequest)(nil),       // 8: trusted_space.kernel.v1.P2PHeartbeatRequest
	(*P2PHeartbeatResponse)(nil),      // 9: trusted_space.kernel.v1.P2PHeartbeatResponse
	(*ConnectorOnlineInfo)(nil),       // 10: trusted_space.kernel.v1.ConnectorOnlineInfo
}
var file_kernel_v1_operator_peer_proto_depIdxs = []int32{
	0,  // 0: trusted_space.kernel.v1.P2PPacket.type:type_name -> trusted_space.kernel.v1.P2PMessageType
	10, // 1: trusted_space.kernel.v1.P2PSyncConnectorsRequest.connectors:type_name -> trusted_space.kernel.v1.ConnectorOnlineInfo
	10, // 2: trusted_space.kernel.v1.P2PSyncConnectorsResponse.remote_connectors:type_name -> trusted_space.kernel.v1.ConnectorOnlineInfo
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kernel_v1_operator_peer_proto_init() }
func file_kernel_v1_operator_peer_proto_init() {
	if File_kernel_v1_operator_peer_proto != nil {
		return
	}
	file_kernel_v1_tempchat_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_v1_operator_peer_proto_rawDesc), len(file_kernel_v1_operator_peer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kernel_v1_operator_peer_proto_goTypes,
		DependencyIndexes: file_kernel_v1_operator_peer_proto_depIdxs,
		EnumInfos:         file_kernel_v1_operator_peer_proto_enumTypes,
		MessageInfos:      file_kernel_v1_operator_peer_proto_msgTypes,
	}.Build()
	File_kernel_v1_operator_peer_proto = out.File
	file_kernel_v1_operator_peer_proto_goTypes = nil
	file_kernel_v1_operator_peer_proto_depIdxs = nil
}
