// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: kernel/v1/tempchat.proto

package kernelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 连接器临时会话注册请求
type RegisterTempSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId    string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`             // 连接器ID
	KernelId       string                 `protobuf:"bytes,2,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                      // 连接器所属内核ID
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                        // 连接器IP地址
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                             // 连接器监听端口
	EntityType     string                 `protobuf:"bytes,5,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                // 连接器实体类型
	ExposeToOthers bool                   `protobuf:"varint,6,opt,name=expose_to_others,json=exposeToOthers,proto3" json:"expose_to_others,omitempty"` // 是否向其他内核暴露
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterTempSessionRequest) Reset() {
	*x = RegisterTempSessionRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTempSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTempSessionRequest) ProtoMessage() {}

func (x *RegisterTempSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTempSessionRequest.ProtoReflect.Descriptor instead.
func (*RegisterTempSessionRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTempSessionRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *RegisterTempSessionRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *RegisterTempSessionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterTempSessionRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterTempSessionRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *RegisterTempSessionRequest) GetExposeToOthers() bool {
	if x != nil {
		return x.ExposeToOthers
	}
	return false
}

// 连接器临时会话注册响应
type RegisterTempSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 分配的会话ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTempSessionResponse) Reset() {
	*x = RegisterTempSessionResponse{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTempSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTempSessionResponse) ProtoMessage() {}

func (x *RegisterTempSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTempSessionResponse.ProtoReflect.Descriptor instead.
func (*RegisterTempSessionResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTempSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterTempSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterTempSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 连接器心跳请求
type TempSessionHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // 会话ID
	ConnectorId   string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 连接器ID
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempSessionHeartbeatRequest) Reset() {
	*x = TempSessionHeartbeatRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempSessionHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempSessionHeartbeatRequest) ProtoMessage() {}

func (x *TempSessionHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempSessionHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*TempSessionHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{2}
}

func (x *TempSessionHeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TempSessionHeartbeatRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *TempSessionHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 连接器心跳响应
type TempSessionHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务器时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempSessionHeartbeatResponse) Reset() {
	*x = TempSessionHeartbeatResponse{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempSessionHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempSessionHeartbeatResponse) ProtoMessage() {}

func (x *TempSessionHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempSessionHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*TempSessionHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{3}
}

func (x *TempSessionHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TempSessionHeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TempSessionHeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 连接器注销会话请求
type UnregisterTempSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // 会话ID
	ConnectorId   string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 连接器ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterTempSessionRequest) Reset() {
	*x = UnregisterTempSessionRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTempSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTempSessionRequest) ProtoMessage() {}

func (x *UnregisterTempSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTempSessionRequest.ProtoReflect.Descriptor instead.
func (*UnregisterTempSessionRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterTempSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UnregisterTempSessionRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

// 连接器注销会话响应
type UnregisterTempSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterTempSessionResponse) Reset() {
	*x = UnregisterTempSessionResponse{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTempSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTempSessionResponse) ProtoMessage() {}

func (x *UnregisterTempSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTempSessionResponse.ProtoReflect.Descriptor instead.
func (*UnregisterTempSessionResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterTempSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterTempSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查询在线连接器请求
type ListOnlineConnectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`        // 请求者ID
	KernelId      string                 `protobuf:"bytes,2,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                 // 指定内核ID（为空表示查询所有）
	IncludeRemote bool                   `protobuf:"varint,3,opt,name=include_remote,json=includeRemote,proto3" json:"include_remote,omitempty"` // 是否包含远程内核的连接器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlineConnectorsRequest) Reset() {
	*x = ListOnlineConnectorsRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlineConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlineConnectorsRequest) ProtoMessage() {}

func (x *ListOnlineConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlineConnectorsRequest.ProtoReflect.Descriptor instead.
func (*ListOnlineConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{6}
}

func (x *ListOnlineConnectorsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ListOnlineConnectorsRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *ListOnlineConnectorsRequest) GetIncludeRemote() bool {
	if x != nil {
		return x.IncludeRemote
	}
	return false
}

// 在线连接器信息
type ConnectorOnlineInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId    string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`             // 连接器ID
	KernelId       string                 `protobuf:"bytes,2,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`                      // 连接器所属内核ID
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                        // 连接器IP地址
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                             // 连接器监听端口
	EntityType     string                 `protobuf:"bytes,5,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                // 连接器实体类型
	SessionId      string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                   // 会话ID
	LastHeartbeat  int64                  `protobuf:"varint,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`      // 最后心跳时间
	RegisteredAt   int64                  `protobuf:"varint,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`         // 注册时间
	ExposeToOthers bool                   `protobuf:"varint,9,opt,name=expose_to_others,json=exposeToOthers,proto3" json:"expose_to_others,omitempty"` // 是否向其他内核暴露
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectorOnlineInfo) Reset() {
	*x = ConnectorOnlineInfo{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorOnlineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorOnlineInfo) ProtoMessage() {}

func (x *ConnectorOnlineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorOnlineInfo.ProtoReflect.Descriptor instead.
func (*ConnectorOnlineInfo) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectorOnlineInfo) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *ConnectorOnlineInfo) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *ConnectorOnlineInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConnectorOnlineInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectorOnlineInfo) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ConnectorOnlineInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectorOnlineInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ConnectorOnlineInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *ConnectorOnlineInfo) GetExposeToOthers() bool {
	if x != nil {
		return x.ExposeToOthers
	}
	return false
}

// 查询在线连接器响应
type ListOnlineConnectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Connectors    []*ConnectorOnlineInfo `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"` // 在线连接器列表
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlineConnectorsResponse) Reset() {
	*x = ListOnlineConnectorsResponse{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlineConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlineConnectorsResponse) ProtoMessage() {}

func (x *ListOnlineConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlineConnectorsResponse.ProtoReflect.Descriptor instead.
func (*ListOnlineConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{8}
}

func (x *ListOnlineConnectorsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListOnlineConnectorsResponse) GetConnectors() []*ConnectorOnlineInfo {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *ListOnlineConnectorsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发送临时消息请求
type SendTempMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`       // 发送者ID
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 接收者ID（目标连接器ID）
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                         // 消息载荷
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // 时间戳
	FlowId        string                 `protobuf:"bytes,5,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`             // 业务流程ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTempMessageRequest) Reset() {
	*x = SendTempMessageRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTempMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTempMessageRequest) ProtoMessage() {}

func (x *SendTempMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTempMessageRequest.ProtoReflect.Descriptor instead.
func (*SendTempMessageRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{9}
}

func (x *SendTempMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendTempMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendTempMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendTempMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendTempMessageRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

// 发送临时消息响应
type SendTempMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 消息ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTempMessageResponse) Reset() {
	*x = SendTempMessageResponse{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTempMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTempMessageResponse) ProtoMessage() {}

func (x *SendTempMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTempMessageResponse.ProtoReflect.Descriptor instead.
func (*SendTempMessageResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{10}
}

func (x *SendTempMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendTempMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendTempMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 接收临时消息请求
type ReceiveTempMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // 连接器ID
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveTempMessageRequest) Reset() {
	*x = ReceiveTempMessageRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveTempMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveTempMessageRequest) ProtoMessage() {}

func (x *ReceiveTempMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveTempMessageRequest.ProtoReflect.Descriptor instead.
func (*ReceiveTempMessageRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{11}
}

func (x *ReceiveTempMessageRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *ReceiveTempMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 临时消息（流式推送）
type TempMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                  // 消息ID
	SenderId       string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                     // 发送者ID
	ReceiverId     string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`               // 接收者ID
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                       // 消息载荷
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // 时间戳
	FlowId         string                 `protobuf:"bytes,6,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`                           // 业务流程ID（可选）
	SourceKernelId string                 `protobuf:"bytes,7,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 源内核ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TempMessage) Reset() {
	*x = TempMessage{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempMessage) ProtoMessage() {}

func (x *TempMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempMessage.ProtoReflect.Descriptor instead.
func (*TempMessage) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{12}
}

func (x *TempMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TempMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *TempMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *TempMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TempMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TempMessage) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *TempMessage) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

// 同步在线连接器请求（运维方之间）
type SyncOnlineConnectorsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceKernelId string                 `protobuf:"bytes,1,opt,name=source_kernel_id,json=sourceKernelId,proto3" json:"source_kernel_id,omitempty"` // 源内核ID
	Connectors     []*ConnectorOnlineInfo `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"`                                 // 本内核在线连接器列表
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // 同步时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncOnlineConnectorsRequest) Reset() {
	*x = SyncOnlineConnectorsRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOnlineConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOnlineConnectorsRequest) ProtoMessage() {}

func (x *SyncOnlineConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOnlineConnectorsRequest.ProtoReflect.Descriptor instead.
func (*SyncOnlineConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{13}
}

func (x *SyncOnlineConnectorsRequest) GetSourceKernelId() string {
	if x != nil {
		return x.SourceKernelId
	}
	return ""
}

func (x *SyncOnlineConnectorsRequest) GetConnectors() []*ConnectorOnlineInfo {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *SyncOnlineConnectorsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 同步在线连接器响应（运维方之间）
type SyncOnlineConnectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOnlineConnectorsResponse) Reset() {
	*x = SyncOnlineConnectorsResponse{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOnlineConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOnlineConnectorsResponse) ProtoMessage() {}

func (x *SyncOnlineConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOnlineConnectorsResponse.ProtoReflect.Descriptor instead.
func (*SyncOnlineConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{14}
}

func (x *SyncOnlineConnectorsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncOnlineConnectorsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 转发临时消息请求（运维方之间）
type ForwardTempMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                     // 原始发送者ID
	SenderKernelId string                 `protobuf:"bytes,2,opt,name=sender_kernel_id,json=senderKernelId,proto3" json:"sender_kernel_id,omitempty"` // 发送者所属内核ID
	ReceiverId     string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`               // 接收者ID（目标连接器ID）
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                       // 消息载荷
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // 时间戳
	FlowId         string                 `protobuf:"bytes,6,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`                           // 业务流程ID（可选）
	MessageId      string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                  // 原始消息ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardTempMessageRequest) Reset() {
	*x = ForwardTempMessageRequest{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardTempMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardTempMessageRequest) ProtoMessage() {}

func (x *ForwardTempMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardTempMessageRequest.ProtoReflect.Descriptor instead.
func (*ForwardTempMessageRequest) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{15}
}

func (x *ForwardTempMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ForwardTempMessageRequest) GetSenderKernelId() string {
	if x != nil {
		return x.SenderKernelId
	}
	return ""
}

func (x *ForwardTempMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ForwardTempMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardTempMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ForwardTempMessageRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ForwardTempMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// 转发临时消息响应（运维方之间）
type ForwardTempMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardTempMessageResponse) Reset() {
	*x = ForwardTempMessageResponse{}
	mi := &file_kernel_v1_tempchat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardTempMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardTempMessageResponse) ProtoMessage() {}

func (x *ForwardTempMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_v1_tempchat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardTempMessageResponse.ProtoReflect.Descriptor instead.
func (*ForwardTempMessageResponse) Descriptor() ([]byte, []int) {
	return file_kernel_v1_tempchat_proto_rawDescGZIP(), []int{16}
}

func (x *ForwardTempMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardTempMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kernel_v1_tempchat_proto protoreflect.FileDescriptor

const file_kernel_v1_tempchat_proto_rawDesc = "" +
	"\n" +
	"\x18kernel/v1/tempchat.proto\x12\x17trusted_space.kernel.v1\"\xd5\x01\n" +
	"\x1aRegisterTempSessionRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1b\n" +
	"\tkernel_id\x18\x02 \x01(\tR\bkernelId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1f\n" +
	"\ventity_type\x18\x05 \x01(\tR\n" +
	"entityType\x12(\n" +
	"\x10expose_to_others\x18\x06 \x01(\bR\x0eexposeToOthers\"p\n" +
	"\x1bRegisterTempSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"}\n" +
	"\x1bTempSessionHeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"s\n" +
	"\x1cTempSessionHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\"`\n" +
	"\x1cUnregisterTempSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\"S\n" +
	"\x1dUnregisterTempSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\x1bListOnlineConnectorsRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1b\n" +
	"\tkernel_id\x18\x02 \x01(\tR\bkernelId\x12%\n" +
	"\x0einclude_remote\x18\x03 \x01(\bR\rincludeRemote\"\xb9\x02\n" +
	"\x13ConnectorOnlineInfo\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1b\n" +
	"\tkernel_id\x18\x02 \x01(\tR\bkernelId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1f\n" +
	"\ventity_type\x18\x05 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12%\n" +
	"\x0elast_heartbeat\x18\a \x01(\x03R\rlastHeartbeat\x12#\n" +
	"\rregistered_at\x18\b \x01(\x03R\fregisteredAt\x12(\n" +
	"\x10expose_to_others\x18\t \x01(\bR\x0eexposeToOthers\"\xa0\x01\n" +
	"\x1cListOnlineConnectorsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12L\n" +
	"\n" +
	"connectors\x18\x02 \x03(\v2,.trusted_space.kernel.v1.ConnectorOnlineInfoR\n" +
	"connectors\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa7\x01\n" +
	"\x16SendTempMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\aflow_id\x18\x05 \x01(\tR\x06flowId\"l\n" +
	"\x17SendTempMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"]\n" +
	"\x19ReceiveTempMessageRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xe5\x01\n" +
	"\vTempMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\aflow_id\x18\x06 \x01(\tR\x06flowId\x12(\n" +
	"\x10source_kernel_id\x18\a \x01(\tR\x0esourceKernelId\"\xb3\x01\n" +
	"\x1bSyncOnlineConnectorsRequest\x12(\n" +
	"\x10source_kernel_id\x18\x01 \x01(\tR\x0esourceKernelId\x12L\n" +
	"\n" +
	"connectors\x18\x02 \x03(\v2,.trusted_space.kernel.v1.ConnectorOnlineInfoR\n" +
	"connectors\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"R\n" +
	"\x1cSyncOnlineConnectorsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf3\x01\n" +
	"\x19ForwardTempMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12(\n" +
	"\x10sender_kernel_id\x18\x02 \x01(\tR\x0esenderKernelId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\aflow_id\x18\x06 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\"P\n" +
	"\x1aForwardTempMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x96\b\n" +
	"\x0fTempChatService\x12\x80\x01\n" +
	"\x13RegisterTempSession\x123.trusted_space.kernel.v1.RegisterTempSessionRequest\x1a4.trusted_space.kernel.v1.RegisterTempSessionResponse\x12\x83\x01\n" +
	"\x14TempSessionHeartbeat\x124.trusted_space.kernel.v1.TempSessionHeartbeatRequest\x1a5.trusted_space.kernel.v1.TempSessionHeartbeatResponse\x12\x86\x01\n" +
	"\x15UnregisterTempSession\x125.trusted_space.kernel.v1.UnregisterTempSessionRequest\x1a6.trusted_space.kernel.v1.UnregisterTempSessionResponse\x12\x83\x01\n" +
	"\x14ListOnlineConnectors\x124.trusted_space.kernel.v1.ListOnlineConnectorsRequest\x1a5.trusted_space.kernel.v1.ListOnlineConnectorsResponse\x12t\n" +
	"\x0fSendTempMessage\x12/.trusted_space.kernel.v1.SendTempMessageRequest\x1a0.trusted_space.kernel.v1.SendTempMessageResponse\x12p\n" +
	"\x12ReceiveTempMessage\x122.trusted_space.kernel.v1.ReceiveTempMessageRequest\x1a$.trusted_space.kernel.v1.TempMessage0\x01\x12\x83\x01\n" +
	"\x14SyncOnlineConnectors\x124.trusted_space.kernel.v1.SyncOnlineConnectorsRequest\x1a5.trusted_space.kernel.v1.SyncOnlineConnectorsResponse\x12}\n" +
	"\x12ForwardTempMessage\x122.trusted_space.kernel.v1.ForwardTempMessageRequest\x1a3.trusted_space.kernel.v1.ForwardTempMessageResponseB1Z/github.com/trusted-space/kernel/api/v1;kernelv1b\x06proto3"

var (
	file_kernel_v1_tempchat_proto_rawDescOnce sync.Once
	file_kernel_v1_tempchat_proto_rawDescData []byte
)

func file_kernel_v1_tempchat_proto_rawDescGZIP() []byte {
	file_kernel_v1_tempchat_proto_rawDescOnce.Do(func() {
		file_kernel_v1_tempchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_v1_tempchat_proto_rawDesc), len(file_kernel_v1_tempchat_proto_rawDesc)))
	})
	return file_kernel_v1_tempchat_proto_rawDescData
}

var file_kernel_v1_tempchat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_kernel_v1_tempchat_proto_goTypes = []any{
	(*RegisterTempSessionRequest)(nil),    // 0: trusted_space.kernel.v1.RegisterTempSessionRequest
	(*RegisterTempSessionResponse)(nil),   // 1: trusted_space.kernel.v1.RegisterTempSessionResponse
	(*TempSessionHeartbeatRequest)(nil),   // 2: trusted_space.kernel.v1.TempSessionHeartbeatRequest
	(*TempSessionHeartbeatResponse)(nil),  // 3: trusted_space.kernel.v1.TempSessionHeartbeatResponse
	(*UnregisterTempSessionRequest)(nil),  // 4: trusted_space.kernel.v1.UnregisterTempSessionRequest
	(*UnregisterTempSessionResponse)(nil), // 5: trusted_space.kernel.v1.UnregisterTempSessionResponse
	(*ListOnlineConnectorsRequest)(nil),   // 6: trusted_space.kernel.v1.ListOnlineConnectorsRequest
	(*ConnectorOnlineInfo)(nil),           // 7: trusted_space.kernel.v1.ConnectorOnlineInfo
	(*ListOnlineConnectorsResponse)(nil),  // 8: trusted_space.kernel.v1.ListOnlineConnectorsResponse
	(*SendTempMessageRequest)(nil),        // 9: trusted_space.kernel.v1.SendTempMessageRequest
	(*SendTempMessageResponse)(nil),       // 10: trusted_space.kernel.v1.SendTempMessageResponse
	(*ReceiveTempMessageRequest)(nil),     // 11: trusted_space.kernel.v1.ReceiveTempMessageRequest
	(*TempMessage)(nil),                   // 12: trusted_space.kernel.v1.TempMessage
	(*SyncOnlineConnectorsRequest)(nil),   // 13: trusted_space.kernel.v1.SyncOnlineConnectorsRequest
	(*SyncOnlineConnectorsResponse)(nil),  // 14: trusted_space.kernel.v1.SyncOnlineConnectorsResponse
	(*ForwardTempMessageRequest)(nil),     // 15: trusted_space.kernel.v1.ForwardTempMessageRequest
	(*ForwardTempMessageResponse)(nil),    // 16: trusted_space.kernel.v1.ForwardTempMessageResponse
}
var file_kernel_v1_tempchat_proto_depIdxs = []int32{
	7,  // 0: trusted_space.kernel.v1.ListOnlineConnectorsResponse.connectors:type_name -> trusted_space.kernel.v1.ConnectorOnlineInfo
	7,  // 1: trusted_space.kernel.v1.SyncOnlineConnectorsRequest.connectors:type_name -> trusted_space.kernel.v1.ConnectorOnlineInfo
	0,  // 2: trusted_space.kernel.v1.TempChatService.RegisterTempSession:input_type -> trusted_space.kernel.v1.RegisterTempSessionRequest
	2,  // 3: trusted_space.kernel.v1.TempChatService.TempSessionHeartbeat:input_type -> trusted_space.kernel.v1.TempSessionHeartbeatRequest
	4,  // 4: trusted_space.kernel.v1.TempChatService.UnregisterTempSession:input_type -> trusted_space.kernel.v1.UnregisterTempSessionRequest
	6,  // 5: trusted_space.kernel.v1.TempChatService.ListOnlineConnectors:input_type -> trusted_space.kernel.v1.ListOnlineConnectorsRequest
	9,  // 6: trusted_space.kernel.v1.TempChatService.SendTempMessage:input_type -> trusted_space.kernel.v1.SendTempMessageRequest
	11, // 7: trusted_space.kernel.v1.TempChatService.ReceiveTempMessage:input_type -> trusted_space.kernel.v1.ReceiveTempMessageRequest
	13, // 8: trusted_space.kernel.v1.TempChatService.SyncOnlineConnectors:input_type -> trusted_space.kernel.v1.SyncOnlineConnectorsRequest
	15, // 9: trusted_space.kernel.v1.TempChatService.ForwardTempMessage:input_type -> trusted_space.kernel.v1.ForwardTempMessageRequest
	1,  // 10: trusted_space.kernel.v1.TempChatService.RegisterTempSession:output_type -> trusted_space.kernel.v1.RegisterTempSessionResponse
	3,  // 11: trusted_space.kernel.v1.TempChatService.TempSessionHeartbeat:output_type -> trusted_space.kernel.v1.TempSessionHeartbeatResponse
	5,  // 12: trusted_space.kernel.v1.TempChatService.UnregisterTempSession:output_type -> trusted_space.kernel.v1.UnregisterTempSessionResponse
	8,  // 13: trusted_space.kernel.v1.TempChatService.ListOnlineConnectors:output_type -> trusted_space.kernel.v1.ListOnlineConnectorsResponse
	10, // 14: trusted_space.kernel.v1.TempChatService.SendTempMessage:output_type -> trusted_space.kernel.v1.SendTempMessageResponse
	12, // 15: trusted_space.kernel.v1.TempChatService.ReceiveTempMessage:output_type -> trusted_space.kernel.v1.TempMessage
	14, // 16: trusted_space.kernel.v1.TempChatService.SyncOnlineConnectors:output_type -> trusted_space.kernel.v1.SyncOnlineConnectorsResponse
	16, // 17: trusted_space.kernel.v1.TempChatService.ForwardTempMessage:output_type -> trusted_space.kernel.v1.ForwardTempMessageResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_kernel_v1_tempchat_proto_init() }
func file_kernel_v1_tempchat_proto_init() {
	if File_kernel_v1_tempchat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_v1_tempchat_proto_rawDesc), len(file_kernel_v1_tempchat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernel_v1_tempchat_proto_goTypes,
		DependencyIndexes: file_kernel_v1_tempchat_proto_depIdxs,
		MessageInfos:      file_kernel_v1_tempchat_proto_msgTypes,
	}.Build()
	File_kernel_v1_tempchat_proto = out.File
	file_kernel_v1_tempchat_proto_goTypes = nil
	file_kernel_v1_tempchat_proto_depIdxs = nil
}
