// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: kernel/v1/tempchat.proto

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TempChatService_RegisterTempSession_FullMethodName   = "/trusted_space.kernel.v1.TempChatService/RegisterTempSession"
	TempChatService_TempSessionHeartbeat_FullMethodName  = "/trusted_space.kernel.v1.TempChatService/TempSessionHeartbeat"
	TempChatService_UnregisterTempSession_FullMethodName = "/trusted_space.kernel.v1.TempChatService/UnregisterTempSession"
	TempChatService_ListOnlineConnectors_FullMethodName  = "/trusted_space.kernel.v1.TempChatService/ListOnlineConnectors"
	TempChatService_SendTempMessage_FullMethodName       = "/trusted_space.kernel.v1.TempChatService/SendTempMessage"
	TempChatService_ReceiveTempMessage_FullMethodName    = "/trusted_space.kernel.v1.TempChatService/ReceiveTempMessage"
	TempChatService_SyncOnlineConnectors_FullMethodName  = "/trusted_space.kernel.v1.TempChatService/SyncOnlineConnectors"
	TempChatService_ForwardTempMessage_FullMethodName    = "/trusted_space.kernel.v1.TempChatService/ForwardTempMessage"
)

// TempChatServiceClient is the client API for TempChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TempChatServiceClient interface {
	// 连接器注册临时会话
	// 连接器启动时调用，上报自己的地址信息（IP:Port）
	RegisterTempSession(ctx context.Context, in *RegisterTempSessionRequest, opts ...grpc.CallOption) (*RegisterTempSessionResponse, error)
	// 连接器心跳保活
	// 连接器定期调用，证明自己仍然在线
	TempSessionHeartbeat(ctx context.Context, in *TempSessionHeartbeatRequest, opts ...grpc.CallOption) (*TempSessionHeartbeatResponse, error)
	// 连接器注销会话
	// 连接器关闭时调用，清理注册信息
	UnregisterTempSession(ctx context.Context, in *UnregisterTempSessionRequest, opts ...grpc.CallOption) (*UnregisterTempSessionResponse, error)
	// 查询在线连接器
	// 查看本内核和跨内核的在线连接器列表（用于 ls 命令展示）
	ListOnlineConnectors(ctx context.Context, in *ListOnlineConnectorsRequest, opts ...grpc.CallOption) (*ListOnlineConnectorsResponse, error)
	// 发送临时消息（连接器 -> 运维方）
	// 连接器通过运维方发送消息给目标连接器
	SendTempMessage(ctx context.Context, in *SendTempMessageRequest, opts ...grpc.CallOption) (*SendTempMessageResponse, error)
	// 接收临时消息（流式，运维方 -> 连接器）
	// 连接器订阅来自运维方的消息推送
	ReceiveTempMessage(ctx context.Context, in *ReceiveTempMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TempMessage], error)
	// 运维方之间同步在线连接器列表
	// 用于跨内核查询在线连接器
	SyncOnlineConnectors(ctx context.Context, in *SyncOnlineConnectorsRequest, opts ...grpc.CallOption) (*SyncOnlineConnectorsResponse, error)
	// 运维方之间转发消息
	// 当目标连接器在远端内核时，通过运维方间通道转发
	ForwardTempMessage(ctx context.Context, in *ForwardTempMessageRequest, opts ...grpc.CallOption) (*ForwardTempMessageResponse, error)
}

type tempChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTempChatServiceClient(cc grpc.ClientConnInterface) TempChatServiceClient {
	return &tempChatServiceClient{cc}
}

func (c *tempChatServiceClient) RegisterTempSession(ctx context.Context, in *RegisterTempSessionRequest, opts ...grpc.CallOption) (*RegisterTempSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTempSessionResponse)
	err := c.cc.Invoke(ctx, TempChatService_RegisterTempSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempChatServiceClient) TempSessionHeartbeat(ctx context.Context, in *TempSessionHeartbeatRequest, opts ...grpc.CallOption) (*TempSessionHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TempSessionHeartbeatResponse)
	err := c.cc.Invoke(ctx, TempChatService_TempSessionHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempChatServiceClient) UnregisterTempSession(ctx context.Context, in *UnregisterTempSessionRequest, opts ...grpc.CallOption) (*UnregisterTempSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterTempSessionResponse)
	err := c.cc.Invoke(ctx, TempChatService_UnregisterTempSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempChatServiceClient) ListOnlineConnectors(ctx context.Context, in *ListOnlineConnectorsRequest, opts ...grpc.CallOption) (*ListOnlineConnectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOnlineConnectorsResponse)
	err := c.cc.Invoke(ctx, TempChatService_ListOnlineConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempChatServiceClient) SendTempMessage(ctx context.Context, in *SendTempMessageRequest, opts ...grpc.CallOption) (*SendTempMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTempMessageResponse)
	err := c.cc.Invoke(ctx, TempChatService_SendTempMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempChatServiceClient) ReceiveTempMessage(ctx context.Context, in *ReceiveTempMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TempMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TempChatService_ServiceDesc.Streams[0], TempChatService_ReceiveTempMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReceiveTempMessageRequest, TempMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TempChatService_ReceiveTempMessageClient = grpc.ServerStreamingClient[TempMessage]

func (c *tempChatServiceClient) SyncOnlineConnectors(ctx context.Context, in *SyncOnlineConnectorsRequest, opts ...grpc.CallOption) (*SyncOnlineConnectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOnlineConnectorsResponse)
	err := c.cc.Invoke(ctx, TempChatService_SyncOnlineConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempChatServiceClient) ForwardTempMessage(ctx context.Context, in *ForwardTempMessageRequest, opts ...grpc.CallOption) (*ForwardTempMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardTempMessageResponse)
	err := c.cc.Invoke(ctx, TempChatService_ForwardTempMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TempChatServiceServer is the server API for TempChatService service.
// All implementations must embed UnimplementedTempChatServiceServer
// for forward compatibility.
type TempChatServiceServer interface {
	// 连接器注册临时会话
	// 连接器启动时调用，上报自己的地址信息（IP:Port）
	RegisterTempSession(context.Context, *RegisterTempSessionRequest) (*RegisterTempSessionResponse, error)
	// 连接器心跳保活
	// 连接器定期调用，证明自己仍然在线
	TempSessionHeartbeat(context.Context, *TempSessionHeartbeatRequest) (*TempSessionHeartbeatResponse, error)
	// 连接器注销会话
	// 连接器关闭时调用，清理注册信息
	UnregisterTempSession(context.Context, *UnregisterTempSessionRequest) (*UnregisterTempSessionResponse, error)
	// 查询在线连接器
	// 查看本内核和跨内核的在线连接器列表（用于 ls 命令展示）
	ListOnlineConnectors(context.Context, *ListOnlineConnectorsRequest) (*ListOnlineConnectorsResponse, error)
	// 发送临时消息（连接器 -> 运维方）
	// 连接器通过运维方发送消息给目标连接器
	SendTempMessage(context.Context, *SendTempMessageRequest) (*SendTempMessageResponse, error)
	// 接收临时消息（流式，运维方 -> 连接器）
	// 连接器订阅来自运维方的消息推送
	ReceiveTempMessage(*ReceiveTempMessageRequest, grpc.ServerStreamingServer[TempMessage]) error
	// 运维方之间同步在线连接器列表
	// 用于跨内核查询在线连接器
	SyncOnlineConnectors(context.Context, *SyncOnlineConnectorsRequest) (*SyncOnlineConnectorsResponse, error)
	// 运维方之间转发消息
	// 当目标连接器在远端内核时，通过运维方间通道转发
	ForwardTempMessage(context.Context, *ForwardTempMessageRequest) (*ForwardTempMessageResponse, error)
	mustEmbedUnimplementedTempChatServiceServer()
}

// UnimplementedTempChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTempChatServiceServer struct{}

func (UnimplementedTempChatServiceServer) RegisterTempSession(context.Context, *RegisterTempSessionRequest) (*RegisterTempSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTempSession not implemented")
}
func (UnimplementedTempChatServiceServer) TempSessionHeartbeat(context.Context, *TempSessionHeartbeatRequest) (*TempSessionHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TempSessionHeartbeat not implemented")
}
func (UnimplementedTempChatServiceServer) UnregisterTempSession(context.Context, *UnregisterTempSessionRequest) (*UnregisterTempSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterTempSession not implemented")
}
func (UnimplementedTempChatServiceServer) ListOnlineConnectors(context.Context, *ListOnlineConnectorsRequest) (*ListOnlineConnectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOnlineConnectors not implemented")
}
func (UnimplementedTempChatServiceServer) SendTempMessage(context.Context, *SendTempMessageRequest) (*SendTempMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTempMessage not implemented")
}
func (UnimplementedTempChatServiceServer) ReceiveTempMessage(*ReceiveTempMessageRequest, grpc.ServerStreamingServer[TempMessage]) error {
	return status.Error(codes.Unimplemented, "method ReceiveTempMessage not implemented")
}
func (UnimplementedTempChatServiceServer) SyncOnlineConnectors(context.Context, *SyncOnlineConnectorsRequest) (*SyncOnlineConnectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncOnlineConnectors not implemented")
}
func (UnimplementedTempChatServiceServer) ForwardTempMessage(context.Context, *ForwardTempMessageRequest) (*ForwardTempMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardTempMessage not implemented")
}
func (UnimplementedTempChatServiceServer) mustEmbedUnimplementedTempChatServiceServer() {}
func (UnimplementedTempChatServiceServer) testEmbeddedByValue()                         {}

// UnsafeTempChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TempChatServiceServer will
// result in compilation errors.
type UnsafeTempChatServiceServer interface {
	mustEmbedUnimplementedTempChatServiceServer()
}

func RegisterTempChatServiceServer(s grpc.ServiceRegistrar, srv TempChatServiceServer) {
	// If the following call panics, it indicates UnimplementedTempChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TempChatService_ServiceDesc, srv)
}

func _TempChatService_RegisterTempSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTempSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempChatServiceServer).RegisterTempSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempChatService_RegisterTempSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempChatServiceServer).RegisterTempSession(ctx, req.(*RegisterTempSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempChatService_TempSessionHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TempSessionHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempChatServiceServer).TempSessionHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempChatService_TempSessionHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempChatServiceServer).TempSessionHeartbeat(ctx, req.(*TempSessionHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempChatService_UnregisterTempSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterTempSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempChatServiceServer).UnregisterTempSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempChatService_UnregisterTempSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempChatServiceServer).UnregisterTempSession(ctx, req.(*UnregisterTempSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempChatService_ListOnlineConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOnlineConnectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempChatServiceServer).ListOnlineConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempChatService_ListOnlineConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempChatServiceServer).ListOnlineConnectors(ctx, req.(*ListOnlineConnectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempChatService_SendTempMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTempMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempChatServiceServer).SendTempMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempChatService_SendTempMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempChatServiceServer).SendTempMessage(ctx, req.(*SendTempMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempChatService_ReceiveTempMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveTempMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TempChatServiceServer).ReceiveTempMessage(m, &grpc.GenericServerStream[ReceiveTempMessageRequest, TempMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TempChatService_ReceiveTempMessageServer = grpc.ServerStreamingServer[TempMessage]

func _TempChatService_SyncOnlineConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOnlineConnectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempChatServiceServer).SyncOnlineConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempChatService_SyncOnlineConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempChatServiceServer).SyncOnlineConnectors(ctx, req.(*SyncOnlineConnectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempChatService_ForwardTempMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardTempMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempChatServiceServer).ForwardTempMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempChatService_ForwardTempMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempChatServiceServer).ForwardTempMessage(ctx, req.(*ForwardTempMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TempChatService_ServiceDesc is the grpc.ServiceDesc for TempChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TempChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trusted_space.kernel.v1.TempChatService",
	HandlerType: (*TempChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTempSession",
			Handler:    _TempChatService_RegisterTempSession_Handler,
		},
		{
			MethodName: "TempSessionHeartbeat",
			Handler:    _TempChatService_TempSessionHeartbeat_Handler,
		},
		{
			MethodName: "UnregisterTempSession",
			Handler:    _TempChatService_UnregisterTempSession_Handler,
		},
		{
			MethodName: "ListOnlineConnectors",
			Handler:    _TempChatService_ListOnlineConnectors_Handler,
		},
		{
			MethodName: "SendTempMessage",
			Handler:    _TempChatService_SendTempMessage_Handler,
		},
		{
			MethodName: "SyncOnlineConnectors",
			Handler:    _TempChatService_SyncOnlineConnectors_Handler,
		},
		{
			MethodName: "ForwardTempMessage",
			Handler:    _TempChatService_ForwardTempMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveTempMessage",
			Handler:       _TempChatService_ReceiveTempMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kernel/v1/tempchat.proto",
}
